import { z } from "zod";
import {
  fisherfolkStatusSchema,
  genderSchema,
  civilStatusSchema,
} from "./enums.js";

export const fisherfolkSchema = z.object({
  id: z.string(),
  tenantId: z.string(),
  registrationNumber: z.string(),
  firstName: z.string().min(1).max(100),
  middleName: z.string().max(100).nullable(),
  lastName: z.string().min(1).max(100),
  suffix: z.string().max(20).nullable(),
  dateOfBirth: z.coerce.date(),
  gender: genderSchema,
  civilStatus: civilStatusSchema,
  nationality: z.string().min(1).max(100),
  contactNumber: z.string().max(20).nullable(),
  email: z.string().email().nullable(),
  barangay: z.string().min(1).max(255),
  address: z.string().min(1),
  educationalAttainment: z.string().nullable(),
  livelihoodType: z.string().min(1),
  organizationMembership: z.string().nullable(),
  photoUrl: z.string().url().nullable(),
  qrCodeData: z.string().nullable(),
  status: fisherfolkStatusSchema,
  statusExpiryDate: z.coerce.date().nullable(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  createdBy: z.string(),
});

export const fisherfolkCreateSchema = z.object({
  tenantId: z.string().min(1),
  registrationNumber: z.string().min(1),
  firstName: z.string().min(1).max(100),
  middleName: z.string().max(100).nullable().optional(),
  lastName: z.string().min(1).max(100),
  suffix: z.string().max(20).nullable().optional(),
  dateOfBirth: z.coerce.date(),
  gender: genderSchema,
  civilStatus: civilStatusSchema,
  nationality: z.string().min(1).max(100),
  contactNumber: z.string().max(20).nullable().optional(),
  email: z.string().email().nullable().optional(),
  barangay: z.string().min(1).max(255),
  address: z.string().min(1),
  educationalAttainment: z.string().nullable().optional(),
  livelihoodType: z.string().min(1),
  organizationMembership: z.string().nullable().optional(),
  photoUrl: z.string().url().nullable().optional(),
  createdBy: z.string().min(1),
});

export const fisherfolkUpdateSchema = z.object({
  firstName: z.string().min(1).max(100).optional(),
  middleName: z.string().max(100).nullable().optional(),
  lastName: z.string().min(1).max(100).optional(),
  suffix: z.string().max(20).nullable().optional(),
  dateOfBirth: z.coerce.date().optional(),
  gender: genderSchema.optional(),
  civilStatus: civilStatusSchema.optional(),
  nationality: z.string().min(1).max(100).optional(),
  contactNumber: z.string().max(20).nullable().optional(),
  email: z.string().email().nullable().optional(),
  barangay: z.string().min(1).max(255).optional(),
  address: z.string().min(1).optional(),
  educationalAttainment: z.string().nullable().optional(),
  livelihoodType: z.string().min(1).optional(),
  organizationMembership: z.string().nullable().optional(),
  photoUrl: z.string().url().nullable().optional(),
  status: fisherfolkStatusSchema.optional(),
  statusExpiryDate: z.coerce.date().nullable().optional(),
});
