// Type Imports
import type { Client } from '@/types/entities/client'

export const db: Client[] = [
  {
    id: 'cust-001',
    name: 'Top Talent',
    industry: 'Retail',
    contactName: 'Bessie Cooper',
    email: 'bessie@toptalent.co',
    phone: '(212) 555-0147',
    billingAccount: 'Top Talent — Net 30',
    avatarInitials: 'TT',
    clientCode: 'TOP-1001',
    legalName: 'Top Talent Retail Group LLC',
    status: 'active',
    accountType: 'key',
    accountManager: 'Sarah Johnson',
    description: 'Multi-store apparel retailer running weekly replenishment into Manhattan storefronts.',
    memberSince: '2019-03-14',
    contactJobTitle: 'Head of Supply Chain',
    contactMobile: '(212) 555-0891',
    preferredContactMethod: 'email',
    city: 'New York',
    state: 'NY',
    country: 'United States',
    billingAddress: '1120 Sixth Avenue, Suite 400\nNew York, NY 10018\nUnited States',
    shippingAddress: '88 Wythe Avenue, Dock 3\nBrooklyn, NY 11249\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 250_000,
    billingEmail: 'ap@toptalent.co',
    taxId: '47-2938471',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Distribution'],
    notes: 'Prefers consolidated weekly deliveries. Store dock access is restricted before 07:00.',
    notesUpdatedBy: 'Sarah Johnson',
    notesUpdatedAt: '2026-07-18',
    documents: [
      { id: 'cdoc-001-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '156 KB', uploadedAt: '2026-01-12' },
      { id: 'cdoc-001-2', name: 'Service Agreement', type: 'pdf', sizeLabel: '842 KB', uploadedAt: '2026-02-03' }
    ],
    activity: [
      {
        id: 'cact-001-1',
        label: 'Weekly replenishment order placed',
        at: '2026-07-21T15:00:00',
        icon: 'shopping-cart'
      },
      { id: 'cact-001-2', label: 'Store delivery completed', at: '2026-07-19T11:40:00', icon: 'truck' },
      { id: 'cact-001-3', label: 'Monthly statement issued', at: '2026-07-15T09:05:00', icon: 'file-text' },
      { id: 'cact-001-4', label: 'Contact details updated by Sarah Johnson', at: '2026-07-11T16:20:00', icon: 'user' }
    ],
    historicalOrders: 142,
    historicalRevenue: 1_620_000
  },
  {
    id: 'cust-002',
    name: 'Ahshav Home',
    industry: 'Furniture',
    contactName: 'Noa Regev',
    email: 'noa@ahshavhome.com',
    phone: '(718) 555-0182',
    billingAccount: 'Ahshav Home — Net 30',
    avatarInitials: 'AH',
    clientCode: 'AHS-1002',
    legalName: 'Ahshav Home Furnishings LLC',
    status: 'active',
    accountType: 'standard',
    accountManager: 'Michael Chen',
    description: 'Furniture importer moving oversized flat-pack freight to showrooms and end customers.',
    memberSince: '2021-08-02',
    contactJobTitle: 'Logistics Manager',
    contactMobile: '(718) 555-0664',
    preferredContactMethod: 'email',
    city: 'Chicago',
    state: 'IL',
    country: 'United States',
    billingAddress: '740 W Fulton Market, Floor 5\nChicago, IL 60607\nUnited States',
    shippingAddress: '3120 S Ashland Avenue, Bay 7\nChicago, IL 60608\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 120_000,
    billingEmail: 'billing@ahshavhome.com',
    taxId: '36-4471028',
    preferredServices: ['Freight Shipping', 'Warehousing'],
    notes: 'Oversized items need a liftgate. Confirm assembly kits ship with the parent carton.',
    notesUpdatedBy: 'Michael Chen',
    notesUpdatedAt: '2026-07-09',
    documents: [{ id: 'cdoc-002-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '148 KB', uploadedAt: '2026-01-22' }],
    activity: [
      { id: 'cact-002-1', label: 'Showroom restock order placed', at: '2026-07-20T10:15:00', icon: 'shopping-cart' },
      { id: 'cact-002-2', label: 'Liftgate delivery dispatched', at: '2026-07-18T08:30:00', icon: 'truck' },
      { id: 'cact-002-3', label: 'Credit limit reviewed', at: '2026-07-12T14:00:00', icon: 'file-text' }
    ],
    historicalOrders: 88,
    historicalRevenue: 946_000
  },
  {
    id: 'cust-003',
    name: 'Aviv Flavor',
    industry: 'Food',
    contactName: 'Dana Peretz',
    email: 'dana@avivflavor.com',
    phone: '(201) 555-0119',
    billingAccount: 'Aviv Flavor — Prepaid',
    avatarInitials: 'AF',
    clientCode: 'AVI-1003',
    legalName: 'Aviv Flavor Foods Inc.',
    status: 'active',
    accountType: 'standard',
    accountManager: 'Emily Davis',
    description: 'Specialty food producer shipping temperature-controlled pallets to regional grocers.',
    memberSince: '2022-05-19',
    contactJobTitle: 'Operations Lead',
    contactMobile: '(201) 555-0733',
    preferredContactMethod: 'phone',
    city: 'Newark',
    state: 'NJ',
    country: 'United States',
    billingAddress: '60 Park Place, Suite 900\nNewark, NJ 07102\nUnited States',
    shippingAddress: '405 Doremus Avenue, Cold Dock 2\nNewark, NJ 07105\nUnited States',
    paymentTerms: 'prepaid',
    currency: 'USD',
    creditLimit: 60_000,
    billingEmail: 'dana@avivflavor.com',
    taxId: '22-3918745',
    preferredServices: ['Freight Shipping', 'Order Fulfillment'],
    notes: 'Chilled loads only. Reject any trailer that cannot hold 4 to 8 degrees Celsius.',
    notesUpdatedBy: 'Emily Davis',
    notesUpdatedAt: '2026-07-16',
    documents: [
      { id: 'cdoc-003-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '151 KB', uploadedAt: '2026-02-14' },
      { id: 'cdoc-003-2', name: 'Credit Application', type: 'pdf', sizeLabel: '388 KB', uploadedAt: '2026-02-14' }
    ],
    activity: [
      { id: 'cact-003-1', label: 'Chilled pallet order placed', at: '2026-07-19T09:45:00', icon: 'shopping-cart' },
      {
        id: 'cact-003-2',
        label: 'Temperature-controlled delivery completed',
        at: '2026-07-14T13:20:00',
        icon: 'truck'
      },
      { id: 'cact-003-3', label: 'Prepaid balance topped up', at: '2026-07-08T10:00:00', icon: 'file-text' }
    ],
    historicalOrders: 61,
    historicalRevenue: 512_000
  },
  {
    id: 'cust-004',
    name: 'Simcha Spa',
    industry: 'Beauty',
    contactName: 'Ronit Levi',
    email: 'ronit@simchaspa.com',
    phone: '(917) 555-0164',
    billingAccount: 'Simcha Spa — Net 15',
    avatarInitials: 'SS',
    clientCode: 'SIM-1004',
    legalName: 'Simcha Spa Holdings LLC',
    status: 'on_hold',
    accountType: 'standard',
    accountManager: 'Daniel Lee',
    description: 'Day-spa chain ordering treatment supplies and retail stock for six locations.',
    memberSince: '2023-01-30',
    contactJobTitle: 'Procurement Manager',
    contactMobile: '(917) 555-0428',
    preferredContactMethod: 'mobile',
    city: 'New York',
    state: 'NY',
    country: 'United States',
    billingAddress: '245 Fifth Avenue, Suite 1102\nNew York, NY 10016\nUnited States',
    shippingAddress: '245 Fifth Avenue, Suite 1102\nNew York, NY 10016\nUnited States',
    paymentTerms: 'net_15',
    currency: 'USD',
    creditLimit: 40_000,
    billingEmail: 'accounts@simchaspa.com',
    taxId: '13-4028816',
    preferredServices: ['Order Fulfillment', 'Returns Management'],
    notes: 'On hold pending settlement of two overdue invoices. Release only with finance sign-off.',
    notesUpdatedBy: 'Daniel Lee',
    notesUpdatedAt: '2026-07-22',
    documents: [
      { id: 'cdoc-004-1', name: 'Credit Application', type: 'pdf', sizeLabel: '402 KB', uploadedAt: '2026-03-05' }
    ],
    activity: [
      { id: 'cact-004-1', label: 'Account placed on hold', at: '2026-07-22T09:10:00', icon: 'user' },
      { id: 'cact-004-2', label: 'Payment overdue notice sent', at: '2026-07-17T08:00:00', icon: 'file-text' },
      { id: 'cact-004-3', label: 'Treatment supply order placed', at: '2026-07-11T11:35:00', icon: 'shopping-cart' }
    ],
    historicalOrders: 47,
    historicalRevenue: 368_000
  },
  {
    id: 'cust-005',
    name: 'Little Haifa',
    industry: 'Fashion',
    contactName: 'Maya Ostrovsky',
    email: 'maya@littlehaifa.com',
    phone: '(347) 555-0173',
    billingAccount: 'Little Haifa — Net 30',
    avatarInitials: 'LH',
    clientCode: 'LIT-1005',
    legalName: 'Little Haifa Apparel Co.',
    status: 'active',
    accountType: 'key',
    accountManager: 'Jason Miller',
    description: 'Direct-to-consumer fashion label with high seasonal peaks and heavy return volume.',
    memberSince: '2018-11-06',
    contactJobTitle: 'Director of Operations',
    contactMobile: '(347) 555-0902',
    preferredContactMethod: 'email',
    city: 'Dallas',
    state: 'TX',
    country: 'United States',
    billingAddress: '2200 Ross Avenue, Suite 1600\nDallas, TX 75201\nUnited States',
    shippingAddress: '4801 Sunbelt Drive, Dock 11\nMesquite, TX 75149\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 300_000,
    billingEmail: 'ap@littlehaifa.com',
    taxId: '75-2277390',
    preferredServices: ['Order Fulfillment', 'Returns Management', 'Distribution'],
    notes: 'Return volume triples in January. Reserve extra reverse-logistics capacity ahead of it.',
    notesUpdatedBy: 'Jason Miller',
    notesUpdatedAt: '2026-07-20',
    documents: [
      { id: 'cdoc-005-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '162 KB', uploadedAt: '2026-01-08' },
      { id: 'cdoc-005-2', name: 'Service Agreement', type: 'pdf', sizeLabel: '911 KB', uploadedAt: '2026-01-08' }
    ],
    activity: [
      { id: 'cact-005-1', label: 'Seasonal drop order placed', at: '2026-07-21T08:20:00', icon: 'shopping-cart' },
      { id: 'cact-005-2', label: 'Parcel consignment delivered', at: '2026-07-18T17:05:00', icon: 'truck' },
      { id: 'cact-005-3', label: 'Return authorisation opened', at: '2026-07-13T10:45:00', icon: 'file-text' },
      { id: 'cact-005-4', label: 'Account manager reassigned to Jason Miller', at: '2026-07-02T09:00:00', icon: 'user' }
    ],
    historicalOrders: 154,
    historicalRevenue: 1_780_000
  },
  {
    id: 'cust-006',
    name: 'Northwind Market',
    industry: 'Grocery',
    contactName: 'Tomer Adin',
    email: 'tomer@northwindmarket.com',
    phone: '(646) 555-0128',
    billingAccount: 'Northwind Market — Net 30',
    avatarInitials: 'NM',
    clientCode: 'NOR-1006',
    legalName: 'Northwind Market Group Inc.',
    status: 'active',
    accountType: 'enterprise',
    accountManager: 'Rachel Adams',
    description: 'Regional grocery chain with daily ambient and chilled replenishment across 40 stores.',
    memberSince: '2017-04-25',
    contactJobTitle: 'VP Supply Chain',
    contactMobile: '(646) 555-0517',
    preferredContactMethod: 'email',
    city: 'Seattle',
    state: 'WA',
    country: 'United States',
    billingAddress: '415 Second Avenue S, Suite 210\nSeattle, WA 98104\nUnited States',
    shippingAddress: '7200 E Marginal Way S, Dock 4\nSeattle, WA 98108\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 450_000,
    billingEmail: 'payables@northwindmarket.com',
    taxId: '91-1836442',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Distribution', 'Consulting'],
    notes: 'Daily 05:00 delivery window at every store. Late arrivals must be phoned ahead.',
    notesUpdatedBy: 'Rachel Adams',
    notesUpdatedAt: '2026-07-21',
    documents: [
      { id: 'cdoc-006-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '1.2 MB', uploadedAt: '2026-01-05' },
      { id: 'cdoc-006-2', name: 'W-9 Form', type: 'pdf', sizeLabel: '158 KB', uploadedAt: '2026-01-05' }
    ],
    activity: [
      {
        id: 'cact-006-1',
        label: 'Daily store replenishment order placed',
        at: '2026-07-21T13:05:00',
        icon: 'shopping-cart'
      },
      { id: 'cact-006-2', label: 'Chilled multi-drop run dispatched', at: '2026-07-20T06:15:00', icon: 'truck' },
      { id: 'cact-006-3', label: 'Quarterly service review filed', at: '2026-07-14T15:30:00', icon: 'file-text' },
      { id: 'cact-006-4', label: 'New store location added to routing', at: '2026-07-06T11:00:00', icon: 'user' }
    ],
    historicalOrders: 198,
    historicalRevenue: 2_640_000
  },
  {
    id: 'cust-007',
    name: 'Aster Living',
    industry: 'Home Decor',
    contactName: 'Shira Katz',
    email: 'shira@asterliving.com',
    phone: '(929) 555-0155',
    billingAccount: 'Aster Living — Prepaid',
    avatarInitials: 'AL',
    clientCode: 'AST-1007',
    legalName: 'Aster Living Decor LLC',
    status: 'active',
    accountType: 'standard',
    accountManager: 'Marcus Bennett',
    description: 'Boutique home-decor brand shipping fragile glassware and ceramics in small parcels.',
    memberSince: '2022-09-12',
    contactJobTitle: 'Founder',
    contactMobile: '(929) 555-0341',
    preferredContactMethod: 'mobile',
    city: 'Malibu',
    state: 'CA',
    country: 'United States',
    billingAddress: '23844 Pacific Coast Highway, Unit 12\nMalibu, CA 90265\nUnited States',
    shippingAddress: '1490 Rosecrans Avenue, Suite 6\nManhattan Beach, CA 90266\nUnited States',
    paymentTerms: 'prepaid',
    currency: 'USD',
    creditLimit: 75_000,
    billingEmail: 'shira@asterliving.com',
    taxId: '95-4712208',
    preferredServices: ['Order Fulfillment', 'Warehousing'],
    notes: 'Every carton is fragile. Never stack above two high and always double-wall glassware.',
    notesUpdatedBy: 'Marcus Bennett',
    notesUpdatedAt: '2026-07-19',
    documents: [{ id: 'cdoc-007-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '144 KB', uploadedAt: '2026-03-19' }],
    activity: [
      { id: 'cact-007-1', label: 'Small-parcel order placed', at: '2026-07-19T11:20:00', icon: 'shopping-cart' },
      { id: 'cact-007-2', label: 'Fragile consignment delivered intact', at: '2026-07-16T14:50:00', icon: 'truck' },
      { id: 'cact-007-3', label: 'Packaging spec updated', at: '2026-07-10T09:30:00', icon: 'file-text' }
    ],
    historicalOrders: 73,
    historicalRevenue: 690_000
  },
  {
    id: 'cust-008',
    name: 'Devtakhum Traders',
    industry: 'Wholesale',
    contactName: 'Ilan Ben-David',
    email: 'ilan@devtakhumtraders.com',
    phone: '(973) 555-0136',
    billingAccount: 'Devtakhum Traders — Net 45',
    avatarInitials: 'DT',
    clientCode: 'DEV-1008',
    legalName: 'Devtakhum Trading Company Inc.',
    status: 'active',
    accountType: 'enterprise',
    accountManager: 'Sofia Alvarez',
    description: 'Import wholesaler clearing containers and cross-docking to independent retailers.',
    memberSince: '2017-10-03',
    contactJobTitle: 'Managing Director',
    contactMobile: '(973) 555-0788',
    preferredContactMethod: 'phone',
    city: 'Newark',
    state: 'NJ',
    country: 'United States',
    billingAddress: '1180 Raymond Boulevard, Floor 8\nNewark, NJ 07102\nUnited States',
    shippingAddress: '900 Corbin Street, Container Yard C\nElizabeth, NJ 07201\nUnited States',
    paymentTerms: 'net_45',
    currency: 'USD',
    creditLimit: 400_000,
    billingEmail: 'finance@devtakhumtraders.com',
    taxId: '22-3550194',
    preferredServices: ['Freight Shipping', 'Customs Brokerage', 'Warehousing', 'Distribution'],
    notes: 'Customs paperwork must be filed 72 hours before vessel arrival. Copy finance on entries.',
    notesUpdatedBy: 'Sofia Alvarez',
    notesUpdatedAt: '2026-07-17',
    documents: [
      { id: 'cdoc-008-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '1.4 MB', uploadedAt: '2026-01-19' },
      { id: 'cdoc-008-2', name: 'Credit Application', type: 'pdf', sizeLabel: '396 KB', uploadedAt: '2026-01-19' }
    ],
    activity: [
      { id: 'cact-008-1', label: 'Container release order placed', at: '2026-07-21T13:40:00', icon: 'shopping-cart' },
      {
        id: 'cact-008-2',
        label: 'Customs entry filed for inbound container',
        at: '2026-07-18T07:25:00',
        icon: 'file-text'
      },
      { id: 'cact-008-3', label: 'Cross-dock transfer in transit', at: '2026-07-17T09:00:00', icon: 'truck' },
      { id: 'cact-008-4', label: 'Payment terms extended to Net 45', at: '2026-07-04T10:15:00', icon: 'user' }
    ],
    historicalOrders: 186,
    historicalRevenue: 2_410_000
  },
  {
    id: 'cust-009',
    name: 'Bloom & Co',
    industry: 'Florist',
    contactName: 'Lior Shani',
    email: 'lior@bloomandco.com',
    phone: '(201) 555-0191',
    billingAccount: 'Bloom & Co — Net 15',
    avatarInitials: 'BC',
    clientCode: 'BLO-1009',
    legalName: 'Bloom and Company Florals LLC',
    status: 'active',
    accountType: 'standard',
    accountManager: 'Sarah Johnson',
    description: 'Event florist needing tightly timed chilled deliveries ahead of morning setups.',
    memberSince: '2023-06-21',
    contactJobTitle: 'Studio Manager',
    contactMobile: '(201) 555-0455',
    preferredContactMethod: 'mobile',
    city: 'Atlanta',
    state: 'GA',
    country: 'United States',
    billingAddress: '191 Peachtree Street NE, Suite 3300\nAtlanta, GA 30303\nUnited States',
    shippingAddress: '1055 Howell Mill Road, Studio B\nAtlanta, GA 30318\nUnited States',
    paymentTerms: 'net_15',
    currency: 'USD',
    creditLimit: 45_000,
    billingEmail: 'lior@bloomandco.com',
    taxId: '58-2904118',
    preferredServices: ['Freight Shipping', 'Order Fulfillment'],
    notes: 'Deliver before the 12:00 setup call. Hold between 4 and 8 degrees Celsius in transit.',
    notesUpdatedBy: 'Sarah Johnson',
    notesUpdatedAt: '2026-07-20',
    documents: [{ id: 'cdoc-009-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '149 KB', uploadedAt: '2026-04-02' }],
    activity: [
      { id: 'cact-009-1', label: 'Event florals order placed', at: '2026-07-20T10:05:00', icon: 'shopping-cart' },
      { id: 'cact-009-2', label: 'Pre-dawn setup delivery completed', at: '2026-07-18T11:15:00', icon: 'truck' },
      { id: 'cact-009-3', label: 'Delivery window preference recorded', at: '2026-07-09T16:40:00', icon: 'file-text' }
    ],
    historicalOrders: 54,
    historicalRevenue: 430_000
  },
  {
    id: 'cust-010',
    name: 'Denim Farms',
    industry: 'Apparel',
    contactName: 'Yossi Mizrahi',
    email: 'yossi@denimfarms.com',
    phone: '(718) 555-0107',
    billingAccount: 'Denim Farms — Net 30',
    avatarInitials: 'DF',
    clientCode: 'DEN-1010',
    legalName: 'Denim Farms Clothing Inc.',
    status: 'inactive',
    accountType: 'key',
    accountManager: 'Michael Chen',
    description: 'Denim wholesaler currently dormant after moving fulfilment in-house.',
    memberSince: '2019-07-08',
    contactJobTitle: 'Head of Distribution',
    contactMobile: '(718) 555-0620',
    preferredContactMethod: 'email',
    city: 'Denver',
    state: 'CO',
    country: 'United States',
    billingAddress: '1550 Wewatta Street, Floor 2\nDenver, CO 80202\nUnited States',
    shippingAddress: '5600 Havana Street, Dock 9\nCommerce City, CO 80022\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 180_000,
    billingEmail: 'ap@denimfarms.com',
    taxId: '84-1996337',
    preferredServices: ['Freight Shipping', 'Warehousing'],
    notes: 'Dormant since May 2026. Keep the record open for a possible peak-season return.',
    notesUpdatedBy: 'Michael Chen',
    notesUpdatedAt: '2026-06-30',
    documents: [
      { id: 'cdoc-010-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '780 KB', uploadedAt: '2025-11-14' },
      { id: 'cdoc-010-2', name: 'W-9 Form', type: 'pdf', sizeLabel: '153 KB', uploadedAt: '2025-11-14' }
    ],
    activity: [
      { id: 'cact-010-1', label: 'Account marked inactive', at: '2026-06-30T09:00:00', icon: 'user' },
      { id: 'cact-010-2', label: 'Final balance settled', at: '2026-06-18T14:20:00', icon: 'file-text' },
      { id: 'cact-010-3', label: 'Last outbound consignment delivered', at: '2026-05-28T10:35:00', icon: 'truck' }
    ],
    historicalOrders: 121,
    historicalRevenue: 1_330_000
  },
  {
    id: 'cust-011',
    name: 'Coastal Grocers',
    industry: 'Grocery',
    contactName: 'Talia Gold',
    email: 'talia@coastalgrocers.com',
    phone: '(212) 555-0169',
    billingAccount: 'Coastal Grocers — Net 30',
    avatarInitials: 'CG',
    clientCode: 'COA-1011',
    legalName: 'Coastal Grocers Holdings Inc.',
    status: 'active',
    accountType: 'enterprise',
    accountManager: 'Emily Davis',
    description: 'Coastal supermarket group running high-volume chilled and frozen distribution.',
    memberSince: '2017-02-16',
    contactJobTitle: 'Chief Operating Officer',
    contactMobile: '(212) 555-0974',
    preferredContactMethod: 'email',
    city: 'Tampa',
    state: 'FL',
    country: 'United States',
    billingAddress: '400 N Ashley Drive, Suite 1900\nTampa, FL 33602\nUnited States',
    shippingAddress: '6202 Adamo Drive, Cold Dock 5\nTampa, FL 33619\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 500_000,
    billingEmail: 'payables@coastalgrocers.com',
    taxId: '59-3128870',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Distribution', 'Consulting'],
    notes: 'Frozen lanes must stay below minus 18 degrees Celsius. Temperature logs required per load.',
    notesUpdatedBy: 'Emily Davis',
    notesUpdatedAt: '2026-07-21',
    documents: [
      { id: 'cdoc-011-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '1.6 MB', uploadedAt: '2026-01-02' },
      { id: 'cdoc-011-2', name: 'Credit Application', type: 'pdf', sizeLabel: '412 KB', uploadedAt: '2026-01-02' }
    ],
    activity: [
      {
        id: 'cact-011-1',
        label: 'Frozen replenishment order placed',
        at: '2026-07-21T09:30:00',
        icon: 'shopping-cart'
      },
      { id: 'cact-011-2', label: 'Multi-temperature load dispatched', at: '2026-07-20T05:45:00', icon: 'truck' },
      { id: 'cact-011-3', label: 'Cold-chain audit passed', at: '2026-07-15T13:00:00', icon: 'file-text' },
      { id: 'cact-011-4', label: 'Credit limit raised to 500,000 USD', at: '2026-07-03T10:20:00', icon: 'user' }
    ],
    historicalOrders: 207,
    historicalRevenue: 2_890_000
  },
  {
    id: 'cust-012',
    name: 'Vertex Outfitters',
    industry: 'Sporting Goods',
    contactName: 'Nicole Barrett',
    email: 'nicole@vertexoutfitters.com',
    phone: '(503) 555-0114',
    billingAccount: 'Vertex Outfitters — Net 30',
    avatarInitials: 'VO',
    clientCode: 'VER-1012',
    legalName: 'Vertex Outfitters Inc.',
    status: 'active',
    accountType: 'key',
    accountManager: 'Daniel Lee',
    description: 'Outdoor equipment retailer with sharp seasonal swings between ski and trail ranges.',
    memberSince: '2020-02-27',
    contactJobTitle: 'Head of Fulfilment',
    contactMobile: '(503) 555-0806',
    preferredContactMethod: 'email',
    city: 'Portland',
    state: 'OR',
    country: 'United States',
    billingAddress: '1000 SW Broadway, Suite 800\nPortland, OR 97205\nUnited States',
    shippingAddress: '7455 N Lombard Street, Dock 2\nPortland, OR 97203\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 260_000,
    billingEmail: 'ap@vertexoutfitters.com',
    taxId: '93-1204558',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Order Fulfillment'],
    notes: 'Ski season doubles outbound volume from October. Book extra trailer capacity early.',
    notesUpdatedBy: 'Daniel Lee',
    notesUpdatedAt: '2026-07-14',
    documents: [
      { id: 'cdoc-012-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '160 KB', uploadedAt: '2026-02-09' },
      { id: 'cdoc-012-2', name: 'Service Agreement', type: 'pdf', sizeLabel: '868 KB', uploadedAt: '2026-02-09' }
    ],
    activity: [
      { id: 'cact-012-1', label: 'Winter range order placed', at: '2026-07-20T14:10:00', icon: 'shopping-cart' },
      { id: 'cact-012-2', label: 'Seasonal stock delivery completed', at: '2026-07-17T16:25:00', icon: 'truck' },
      { id: 'cact-012-3', label: 'Seasonal capacity plan shared', at: '2026-07-10T11:50:00', icon: 'file-text' }
    ],
    historicalOrders: 133,
    historicalRevenue: 1_495_000
  },
  {
    id: 'cust-013',
    name: 'Harborline Foods',
    industry: 'Food Distribution',
    contactName: 'Owen Fitzgerald',
    email: 'owen@harborlinefoods.com',
    phone: '(617) 555-0138',
    billingAccount: 'Harborline Foods — Net 45',
    avatarInitials: 'HF',
    clientCode: 'HAR-1013',
    legalName: 'Harborline Foods Distribution LLC',
    status: 'on_hold',
    accountType: 'standard',
    accountManager: 'Jason Miller',
    description: 'Seafood distributor supplying restaurants along the New England corridor.',
    memberSince: '2021-11-15',
    contactJobTitle: 'Distribution Manager',
    contactMobile: '(617) 555-0723',
    preferredContactMethod: 'phone',
    city: 'Boston',
    state: 'MA',
    country: 'United States',
    billingAddress: '265 Franklin Street, Floor 12\nBoston, MA 02110\nUnited States',
    shippingAddress: '12 Fish Pier Road, Cold Dock 1\nBoston, MA 02210\nUnited States',
    paymentTerms: 'net_45',
    currency: 'USD',
    creditLimit: 130_000,
    billingEmail: 'accounts@harborlinefoods.com',
    taxId: '04-3377621',
    preferredServices: ['Freight Shipping', 'Distribution'],
    notes: 'On hold while the renewed cold-chain insurance certificate is outstanding.',
    notesUpdatedBy: 'Jason Miller',
    notesUpdatedAt: '2026-07-13',
    documents: [
      { id: 'cdoc-013-1', name: 'Credit Application', type: 'pdf', sizeLabel: '374 KB', uploadedAt: '2026-03-28' }
    ],
    activity: [
      { id: 'cact-013-1', label: 'Account placed on hold', at: '2026-07-13T08:45:00', icon: 'user' },
      { id: 'cact-013-2', label: 'Insurance certificate requested', at: '2026-07-09T12:15:00', icon: 'file-text' },
      { id: 'cact-013-3', label: 'Overnight seafood delivery completed', at: '2026-07-06T07:30:00', icon: 'truck' }
    ],
    historicalOrders: 96,
    historicalRevenue: 1_020_000
  },
  {
    id: 'cust-014',
    name: 'Pinecrest Pharma',
    industry: 'Pharmaceuticals',
    contactName: 'Alicia Moreno',
    email: 'alicia@pinecrestpharma.com',
    phone: '(602) 555-0176',
    billingAccount: 'Pinecrest Pharma — Net 60',
    avatarInitials: 'PP',
    clientCode: 'PIN-1014',
    legalName: 'Pinecrest Pharmaceuticals Inc.',
    status: 'active',
    accountType: 'enterprise',
    accountManager: 'Rachel Adams',
    description: 'Pharmaceutical manufacturer shipping validated cold-chain loads under strict audit.',
    memberSince: '2018-05-09',
    contactJobTitle: 'Director of Distribution',
    contactMobile: '(602) 555-0489',
    preferredContactMethod: 'email',
    city: 'Phoenix',
    state: 'AZ',
    country: 'United States',
    billingAddress: '2 N Central Avenue, Suite 1800\nPhoenix, AZ 85004\nUnited States',
    shippingAddress: '4400 S 40th Street, Validated Dock A\nPhoenix, AZ 85040\nUnited States',
    paymentTerms: 'net_60',
    currency: 'USD',
    creditLimit: 420_000,
    billingEmail: 'payables@pinecrestpharma.com',
    taxId: '86-0914773',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Customs Brokerage', 'Consulting'],
    notes: 'Only validated cold-chain equipment. Every load needs a signed temperature log on arrival.',
    notesUpdatedBy: 'Rachel Adams',
    notesUpdatedAt: '2026-07-19',
    documents: [
      { id: 'cdoc-014-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '2.1 MB', uploadedAt: '2026-01-15' },
      { id: 'cdoc-014-2', name: 'W-9 Form', type: 'pdf', sizeLabel: '157 KB', uploadedAt: '2026-01-15' }
    ],
    activity: [
      {
        id: 'cact-014-1',
        label: 'Validated cold-chain order placed',
        at: '2026-07-21T10:40:00',
        icon: 'shopping-cart'
      },
      { id: 'cact-014-2', label: 'Temperature-logged load dispatched', at: '2026-07-19T06:00:00', icon: 'truck' },
      { id: 'cact-014-3', label: 'GDP compliance audit passed', at: '2026-07-12T15:20:00', icon: 'file-text' },
      { id: 'cact-014-4', label: 'Validated lane added for Tucson', at: '2026-07-05T09:45:00', icon: 'user' }
    ],
    historicalOrders: 178,
    historicalRevenue: 2_490_000
  },
  {
    id: 'cust-015',
    name: 'Lumen Electronics',
    industry: 'Electronics',
    contactName: 'Wesley Park',
    email: 'wesley@lumenelectronics.com',
    phone: '(206) 555-0143',
    billingAccount: 'Lumen Electronics — Net 30',
    avatarInitials: 'LE',
    clientCode: 'LUM-1015',
    legalName: 'Lumen Electronics Corporation',
    status: 'active',
    accountType: 'enterprise',
    accountManager: 'Marcus Bennett',
    description: 'Consumer electronics brand moving high-value freight with serial-level tracking.',
    memberSince: '2018-08-30',
    contactJobTitle: 'Global Logistics Director',
    contactMobile: '(206) 555-0592',
    preferredContactMethod: 'email',
    city: 'Seattle',
    state: 'WA',
    country: 'United States',
    billingAddress: '1201 Third Avenue, Suite 2200\nSeattle, WA 98101\nUnited States',
    shippingAddress: '18200 Andover Park W, Dock 6\nTukwila, WA 98188\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 380_000,
    billingEmail: 'ap@lumenelectronics.com',
    taxId: '91-2044619',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Customs Brokerage', 'Returns Management'],
    notes: 'High-value loads need sealed trailers and a serial scan at both pickup and delivery.',
    notesUpdatedBy: 'Marcus Bennett',
    notesUpdatedAt: '2026-07-20',
    documents: [
      { id: 'cdoc-015-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '1.8 MB', uploadedAt: '2026-01-27' },
      { id: 'cdoc-015-2', name: 'Credit Application', type: 'pdf', sizeLabel: '408 KB', uploadedAt: '2026-01-27' }
    ],
    activity: [
      { id: 'cact-015-1', label: 'High-value freight order placed', at: '2026-07-20T12:35:00', icon: 'shopping-cart' },
      { id: 'cact-015-2', label: 'Serial-scanned delivery completed', at: '2026-07-18T15:10:00', icon: 'truck' },
      {
        id: 'cact-015-3',
        label: 'Security escort booked for high-value lane',
        at: '2026-07-13T08:55:00',
        icon: 'file-text'
      },
      { id: 'cact-015-4', label: 'Returns process updated', at: '2026-07-07T14:05:00', icon: 'user' }
    ],
    historicalOrders: 165,
    historicalRevenue: 2_310_000
  },
  {
    id: 'cust-016',
    name: 'Sable Ridge Jewelers',
    industry: 'Jewelry',
    contactName: 'Nadia Haddad',
    email: 'nadia@sableridge.com',
    phone: '(312) 555-0159',
    billingAccount: 'Sable Ridge Jewelers — Prepaid',
    avatarInitials: 'SR',
    clientCode: 'SAB-1016',
    legalName: 'Sable Ridge Jewelers LLC',
    status: 'active',
    accountType: 'standard',
    accountManager: 'Sofia Alvarez',
    description: 'Fine jewelry house shipping small insured parcels with signature-on-delivery.',
    memberSince: '2024-01-18',
    contactJobTitle: 'Operations Director',
    contactMobile: '(312) 555-0930',
    preferredContactMethod: 'mobile',
    city: 'Chicago',
    state: 'IL',
    country: 'United States',
    billingAddress: '333 N Michigan Avenue, Suite 2400\nChicago, IL 60601\nUnited States',
    shippingAddress: '333 N Michigan Avenue, Suite 2400\nChicago, IL 60601\nUnited States',
    paymentTerms: 'prepaid',
    currency: 'USD',
    creditLimit: 30_000,
    billingEmail: 'nadia@sableridge.com',
    taxId: '36-4988052',
    preferredServices: ['Order Fulfillment', 'Returns Management'],
    notes: 'Signature on delivery is mandatory. Never leave a parcel with a building concierge.',
    notesUpdatedBy: 'Sofia Alvarez',
    notesUpdatedAt: '2026-07-15',
    documents: [{ id: 'cdoc-016-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '141 KB', uploadedAt: '2026-04-11' }],
    activity: [
      { id: 'cact-016-1', label: 'Insured parcel order placed', at: '2026-07-18T13:25:00', icon: 'shopping-cart' },
      { id: 'cact-016-2', label: 'Signature-on-delivery confirmed', at: '2026-07-16T10:40:00', icon: 'truck' },
      { id: 'cact-016-3', label: 'Insurance rider added to account', at: '2026-07-08T11:30:00', icon: 'file-text' }
    ],
    historicalOrders: 42,
    historicalRevenue: 336_000
  },
  {
    id: 'cust-017',
    name: 'Redwood Brewing',
    industry: 'Beverages',
    contactName: 'Cormac Blythe',
    email: 'cormac@redwoodbrewing.com',
    phone: '(503) 555-0187',
    billingAccount: 'Redwood Brewing — Net 15',
    avatarInitials: 'RB',
    clientCode: 'RED-1017',
    legalName: 'Redwood Brewing Company LLC',
    status: 'inactive',
    accountType: 'standard',
    accountManager: 'Sarah Johnson',
    description: 'Craft brewery paused after consolidating distribution with a regional partner.',
    memberSince: '2022-03-07',
    contactJobTitle: 'Distribution Lead',
    contactMobile: '(503) 555-0271',
    preferredContactMethod: 'email',
    city: 'Portland',
    state: 'OR',
    country: 'United States',
    billingAddress: '2130 NW Quimby Street, Suite 5\nPortland, OR 97210\nUnited States',
    shippingAddress: '2130 NW Quimby Street, Loading Bay\nPortland, OR 97210\nUnited States',
    paymentTerms: 'net_15',
    currency: 'USD',
    creditLimit: 65_000,
    billingEmail: 'cormac@redwoodbrewing.com',
    taxId: '93-1687244',
    preferredServices: ['Freight Shipping', 'Distribution'],
    notes: 'Paused in June 2026 pending the outcome of their distributor consolidation.',
    notesUpdatedBy: 'Sarah Johnson',
    notesUpdatedAt: '2026-06-24',
    documents: [{ id: 'cdoc-017-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '147 KB', uploadedAt: '2025-09-30' }],
    activity: [
      { id: 'cact-017-1', label: 'Account marked inactive', at: '2026-06-24T10:00:00', icon: 'user' },
      { id: 'cact-017-2', label: 'Closing statement issued', at: '2026-06-15T13:45:00', icon: 'file-text' },
      { id: 'cact-017-3', label: 'Final keg consignment delivered', at: '2026-06-02T09:20:00', icon: 'truck' }
    ],
    historicalOrders: 68,
    historicalRevenue: 578_000
  },
  {
    id: 'cust-018',
    name: 'Atlas Auto Parts',
    industry: 'Automotive',
    contactName: 'Derek Vaughn',
    email: 'derek@atlasautoparts.com',
    phone: '(214) 555-0122',
    billingAccount: 'Atlas Auto Parts — Net 60',
    avatarInitials: 'AA',
    clientCode: 'ATL-1018',
    legalName: 'Atlas Auto Parts Inc.',
    status: 'active',
    accountType: 'key',
    accountManager: 'Michael Chen',
    description: 'Aftermarket parts supplier shipping dense palletised freight to trade counters.',
    memberSince: '2019-10-21',
    contactJobTitle: 'Supply Chain Manager',
    contactMobile: '(214) 555-0847',
    preferredContactMethod: 'phone',
    city: 'Dallas',
    state: 'TX',
    country: 'United States',
    billingAddress: '1717 Main Street, Suite 3100\nDallas, TX 75201\nUnited States',
    shippingAddress: '2900 S Great Southwest Parkway, Dock 14\nGrand Prairie, TX 75051\nUnited States',
    paymentTerms: 'net_60',
    currency: 'USD',
    creditLimit: 275_000,
    billingEmail: 'ap@atlasautoparts.com',
    taxId: '75-2811906',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Distribution'],
    notes: 'Pallets run heavy. Confirm axle weights before dispatch to avoid roadside penalties.',
    notesUpdatedBy: 'Michael Chen',
    notesUpdatedAt: '2026-07-18',
    documents: [
      { id: 'cdoc-018-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '155 KB', uploadedAt: '2026-02-20' },
      { id: 'cdoc-018-2', name: 'Credit Application', type: 'pdf', sizeLabel: '391 KB', uploadedAt: '2026-02-20' }
    ],
    activity: [
      { id: 'cact-018-1', label: 'Palletised parts order placed', at: '2026-07-20T08:50:00', icon: 'shopping-cart' },
      { id: 'cact-018-2', label: 'Trade counter delivery dispatched', at: '2026-07-19T07:10:00', icon: 'truck' },
      { id: 'cact-018-3', label: 'Payment terms extended to Net 60', at: '2026-07-11T10:30:00', icon: 'file-text' }
    ],
    historicalOrders: 149,
    historicalRevenue: 1_715_000
  },
  {
    id: 'cust-019',
    name: 'Willow Paper Co',
    industry: 'Paper Goods',
    contactName: 'Ingrid Solberg',
    email: 'ingrid@willowpaper.com',
    phone: '(404) 555-0195',
    billingAccount: 'Willow Paper Co — Net 30',
    avatarInitials: 'WP',
    clientCode: 'WIL-1019',
    legalName: 'Willow Paper Company LLC',
    status: 'on_hold',
    accountType: 'standard',
    accountManager: 'Emily Davis',
    description: 'Stationery manufacturer shipping bulk reams and packaging stock to print shops.',
    memberSince: '2021-04-13',
    contactJobTitle: 'Warehouse Manager',
    contactMobile: '(404) 555-0368',
    preferredContactMethod: 'email',
    city: 'Atlanta',
    state: 'GA',
    country: 'United States',
    billingAddress: '3344 Peachtree Road NE, Suite 800\nAtlanta, GA 30326\nUnited States',
    shippingAddress: '4180 Fulton Industrial Boulevard, Dock 3\nAtlanta, GA 30336\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 95_000,
    billingEmail: 'billing@willowpaper.com',
    taxId: '58-2455189',
    preferredServices: ['Freight Shipping', 'Warehousing'],
    notes: 'On hold during a billing dispute over three duplicated freight charges.',
    notesUpdatedBy: 'Emily Davis',
    notesUpdatedAt: '2026-07-16',
    documents: [{ id: 'cdoc-019-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '150 KB', uploadedAt: '2026-03-11' }],
    activity: [
      { id: 'cact-019-1', label: 'Account placed on hold', at: '2026-07-16T11:05:00', icon: 'user' },
      { id: 'cact-019-2', label: 'Billing dispute opened', at: '2026-07-14T09:40:00', icon: 'file-text' },
      { id: 'cact-019-3', label: 'Bulk paper delivery completed', at: '2026-07-10T14:15:00', icon: 'truck' }
    ],
    historicalOrders: 82,
    historicalRevenue: 812_000
  },
  {
    id: 'cust-020',
    name: 'Kestrel Toys',
    industry: 'Toys',
    contactName: 'Marco Delgado',
    email: 'marco@kestreltoys.com',
    phone: '(303) 555-0131',
    billingAccount: 'Kestrel Toys — Net 15',
    avatarInitials: 'KT',
    clientCode: 'KES-1020',
    legalName: 'Kestrel Toys LLC',
    status: 'active',
    accountType: 'standard',
    accountManager: 'Daniel Lee',
    description: 'Independent toy brand with a heavy fourth-quarter peak into online marketplaces.',
    memberSince: '2023-09-04',
    contactJobTitle: 'Fulfilment Manager',
    contactMobile: '(303) 555-0715',
    preferredContactMethod: 'email',
    city: 'Denver',
    state: 'CO',
    country: 'United States',
    billingAddress: '1401 Lawrence Street, Suite 1100\nDenver, CO 80202\nUnited States',
    shippingAddress: '9200 E 40th Avenue, Dock 5\nDenver, CO 80238\nUnited States',
    paymentTerms: 'net_15',
    currency: 'USD',
    creditLimit: 50_000,
    billingEmail: 'marco@kestreltoys.com',
    taxId: '84-2703441',
    preferredServices: ['Order Fulfillment', 'Distribution', 'Returns Management'],
    notes: 'Marketplace labels must be applied before pickup. Peak volume starts mid-September.',
    notesUpdatedBy: 'Daniel Lee',
    notesUpdatedAt: '2026-07-12',
    documents: [
      { id: 'cdoc-020-1', name: 'Credit Application', type: 'pdf', sizeLabel: '380 KB', uploadedAt: '2026-05-06' }
    ],
    activity: [
      { id: 'cact-020-1', label: 'Marketplace restock order placed', at: '2026-07-19T15:30:00', icon: 'shopping-cart' },
      { id: 'cact-020-2', label: 'Fulfilment centre delivery completed', at: '2026-07-17T12:00:00', icon: 'truck' },
      { id: 'cact-020-3', label: 'Marketplace label spec received', at: '2026-07-12T10:10:00', icon: 'file-text' }
    ],
    historicalOrders: 57,
    historicalRevenue: 462_000
  },
  {
    id: 'cust-021',
    name: 'Ironvale Hardware',
    industry: 'Hardware',
    contactName: 'Bianca Rossi',
    email: 'bianca@ironvalehardware.com',
    phone: '(602) 555-0148',
    billingAccount: 'Ironvale Hardware — Net 45',
    avatarInitials: 'IH',
    clientCode: 'IRO-1021',
    legalName: 'Ironvale Hardware Supply Inc.',
    status: 'active',
    accountType: 'key',
    accountManager: 'Jason Miller',
    description: 'Builders merchant moving heavy fixings and tooling to trade sites across the Southwest.',
    memberSince: '2020-06-17',
    contactJobTitle: 'Head of Procurement',
    contactMobile: '(602) 555-0983',
    preferredContactMethod: 'phone',
    city: 'Phoenix',
    state: 'AZ',
    country: 'United States',
    billingAddress: '100 W Washington Street, Suite 1400\nPhoenix, AZ 85003\nUnited States',
    shippingAddress: '3050 S 51st Avenue, Yard 2\nPhoenix, AZ 85043\nUnited States',
    paymentTerms: 'net_45',
    currency: 'USD',
    creditLimit: 220_000,
    billingEmail: 'ap@ironvalehardware.com',
    taxId: '86-1339077',
    preferredServices: ['Freight Shipping', 'Warehousing', 'Distribution'],
    notes: 'Site deliveries need a forklift on arrival. Call the site foreman thirty minutes out.',
    notesUpdatedBy: 'Jason Miller',
    notesUpdatedAt: '2026-07-17',
    documents: [
      { id: 'cdoc-021-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '922 KB', uploadedAt: '2026-02-26' },
      { id: 'cdoc-021-2', name: 'W-9 Form', type: 'pdf', sizeLabel: '154 KB', uploadedAt: '2026-02-26' }
    ],
    activity: [
      { id: 'cact-021-1', label: 'Site materials order placed', at: '2026-07-20T09:25:00', icon: 'shopping-cart' },
      { id: 'cact-021-2', label: 'Heavy goods load dispatched', at: '2026-07-19T06:40:00', icon: 'truck' },
      { id: 'cact-021-3', label: 'Site access instructions updated', at: '2026-07-15T14:35:00', icon: 'file-text' },
      { id: 'cact-021-4', label: 'Second delivery yard registered', at: '2026-07-06T10:50:00', icon: 'user' }
    ],
    historicalOrders: 128,
    historicalRevenue: 1_408_000
  },
  {
    id: 'cust-022',
    name: 'Solstice Textiles',
    industry: 'Textiles',
    contactName: 'Hugo Lindqvist',
    email: 'hugo@solsticetextiles.com',
    phone: '(617) 555-0166',
    billingAccount: 'Solstice Textiles — Net 30',
    avatarInitials: 'ST',
    clientCode: 'SOL-1022',
    legalName: 'Solstice Textiles LLC',
    status: 'on_hold',
    accountType: 'standard',
    accountManager: 'Rachel Adams',
    description: 'Fabric importer supplying upholstery mills with roll goods and trim.',
    memberSince: '2022-12-01',
    contactJobTitle: 'Import Coordinator',
    contactMobile: '(617) 555-0294',
    preferredContactMethod: 'email',
    city: 'Boston',
    state: 'MA',
    country: 'United States',
    billingAddress: '101 Federal Street, Floor 19\nBoston, MA 02110\nUnited States',
    shippingAddress: '600 Rear Broadway, Bay 4\nEverett, MA 02149\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 110_000,
    billingEmail: 'accounts@solsticetextiles.com',
    taxId: '04-3812650',
    preferredServices: ['Freight Shipping', 'Customs Brokerage', 'Warehousing'],
    notes: 'On hold until the updated customs power of attorney is returned and countersigned.',
    notesUpdatedBy: 'Rachel Adams',
    notesUpdatedAt: '2026-07-11',
    documents: [
      { id: 'cdoc-022-1', name: 'Credit Application', type: 'pdf', sizeLabel: '385 KB', uploadedAt: '2026-04-23' }
    ],
    activity: [
      { id: 'cact-022-1', label: 'Account placed on hold', at: '2026-07-11T09:15:00', icon: 'user' },
      { id: 'cact-022-2', label: 'Customs power of attorney requested', at: '2026-07-08T13:50:00', icon: 'file-text' },
      { id: 'cact-022-3', label: 'Roll goods delivery completed', at: '2026-07-03T11:25:00', icon: 'truck' }
    ],
    historicalOrders: 91,
    historicalRevenue: 928_000
  },
  {
    id: 'cust-023',
    name: 'Brightpath Books',
    industry: 'Publishing',
    contactName: 'Camille Duforest',
    email: 'camille@brightpathbooks.com',
    phone: '(310) 555-0179',
    billingAccount: 'Brightpath Books — Prepaid',
    avatarInitials: 'BB',
    clientCode: 'BRI-1023',
    legalName: 'Brightpath Books LLC',
    status: 'active',
    accountType: 'standard',
    accountManager: 'Marcus Bennett',
    description: 'Independent publisher shipping print runs to distributors and direct subscribers.',
    memberSince: '2024-04-08',
    contactJobTitle: 'Operations Coordinator',
    contactMobile: '(310) 555-0836',
    preferredContactMethod: 'email',
    city: 'Malibu',
    state: 'CA',
    country: 'United States',
    billingAddress: '22729 Pacific Coast Highway, Unit 4\nMalibu, CA 90265\nUnited States',
    shippingAddress: '1800 E Grand Avenue, Dock 1\nEl Segundo, CA 90245\nUnited States',
    paymentTerms: 'prepaid',
    currency: 'USD',
    creditLimit: 25_000,
    billingEmail: 'camille@brightpathbooks.com',
    taxId: '95-4033712',
    preferredServices: ['Order Fulfillment', 'Distribution'],
    notes: 'Print runs arrive shrink-wrapped on pallets. Keep skids dry and off bare concrete.',
    notesUpdatedBy: 'Marcus Bennett',
    notesUpdatedAt: '2026-07-10',
    documents: [{ id: 'cdoc-023-1', name: 'W-9 Form', type: 'pdf', sizeLabel: '143 KB', uploadedAt: '2026-05-19' }],
    activity: [
      {
        id: 'cact-023-1',
        label: 'Print run distribution order placed',
        at: '2026-07-17T10:20:00',
        icon: 'shopping-cart'
      },
      { id: 'cact-023-2', label: 'Distributor delivery completed', at: '2026-07-15T09:35:00', icon: 'truck' },
      { id: 'cact-023-3', label: 'Prepaid balance topped up', at: '2026-07-10T08:05:00', icon: 'file-text' }
    ],
    historicalOrders: 45,
    historicalRevenue: 351_000
  },
  {
    id: 'cust-024',
    name: 'Marisol Cosmetics',
    industry: 'Cosmetics',
    contactName: 'Yuki Tanaka',
    email: 'yuki@marisolcosmetics.com',
    phone: '(813) 555-0152',
    billingAccount: 'Marisol Cosmetics — Net 30',
    avatarInitials: 'MC',
    clientCode: 'MAR-1024',
    legalName: 'Marisol Cosmetics Inc.',
    status: 'inactive',
    accountType: 'key',
    accountManager: 'Sofia Alvarez',
    description: 'Cosmetics brand dormant while it rebuilds its retail distribution agreements.',
    memberSince: '2020-10-14',
    contactJobTitle: 'Head of Logistics',
    contactMobile: '(813) 555-0407',
    preferredContactMethod: 'email',
    city: 'Tampa',
    state: 'FL',
    country: 'United States',
    billingAddress: '100 S Ashley Drive, Suite 600\nTampa, FL 33602\nUnited States',
    shippingAddress: '5100 W Hillsborough Avenue, Dock 8\nTampa, FL 33634\nUnited States',
    paymentTerms: 'net_30',
    currency: 'USD',
    creditLimit: 160_000,
    billingEmail: 'ap@marisolcosmetics.com',
    taxId: '59-3744825',
    preferredServices: ['Freight Shipping', 'Order Fulfillment', 'Returns Management'],
    notes: 'Dormant since May 2026. Aerosol lines require hazmat paperwork if the account reopens.',
    notesUpdatedBy: 'Sofia Alvarez',
    notesUpdatedAt: '2026-06-12',
    documents: [
      { id: 'cdoc-024-1', name: 'Service Agreement', type: 'pdf', sizeLabel: '804 KB', uploadedAt: '2025-10-08' },
      { id: 'cdoc-024-2', name: 'W-9 Form', type: 'pdf', sizeLabel: '152 KB', uploadedAt: '2025-10-08' }
    ],
    activity: [
      { id: 'cact-024-1', label: 'Account marked inactive', at: '2026-06-12T09:30:00', icon: 'user' },
      { id: 'cact-024-2', label: 'Hazmat certification archived', at: '2026-06-05T15:00:00', icon: 'file-text' },
      { id: 'cact-024-3', label: 'Final retail delivery completed', at: '2026-05-21T13:10:00', icon: 'truck' }
    ],
    historicalOrders: 110,
    historicalRevenue: 1_210_000
  }
]
