// Type Imports
import type {
  Driver,
  DriverActivityEntry,
  DriverAssignedVehicle,
  DriverDocument,
  DriverTrip
} from '@/types/entities/driver'
import type { Vehicle } from '@/types/entities/vehicle'

// Data Imports
import { db as vehiclesDb } from '@/fake-db/entities/vehicles'

// Vars
const shiftDate = (base: string, days: number): string => {
  const d = new Date(base)

  d.setUTCDate(d.getUTCDate() + days)

  return d.toISOString().slice(0, 10)
}

const buildDocs = (
  seq: number,
  licenseNumber: string,
  licenseExpiry: string,
  medicalCardExpiry: string,
  drugTestDue: string
): DriverDocument[] => [
  { type: 'license', number: licenseNumber, issuedOn: shiftDate(licenseExpiry, -1460), expiry: licenseExpiry },
  {
    type: 'medical_card',
    number: `MED-${700100 + seq * 137}`,
    issuedOn: shiftDate(medicalCardExpiry, -730),
    expiry: medicalCardExpiry
  },
  {
    type: 'background_check',
    number: `BGC-${540200 + seq * 211}`,
    issuedOn: shiftDate(drugTestDue, -540),
    expiry: shiftDate(drugTestDue, 300)
  },
  {
    type: 'drug_test',
    number: `DOT-${910300 + seq * 173}`,
    issuedOn: shiftDate(drugTestDue, -180),
    expiry: drugTestDue
  }
]

const trip = (
  id: string,
  n: number,
  date: string,
  shipmentId: string,
  origin: string,
  destination: string,
  distanceKm: number,
  durationLabel: string,
  status: DriverTrip['status']
): DriverTrip => ({
  id: `${id}-trip-${n}`,
  date,
  shipmentId,
  origin,
  destination,
  distanceKm,
  durationLabel,
  onTime: status === 'completed',
  status
})

const buildTrips = (
  id: string,
  origin: string,
  destination: string,
  km: number,
  dur: string,
  baseNum: number
): DriverTrip[] => [
  trip(id, 1, '2026-08-01', `SHP-${baseNum}`, origin, destination, km, dur, 'completed'),
  trip(id, 2, '2026-07-30', `SHP-${baseNum - 14}`, destination, origin, km, dur, 'completed'),
  trip(id, 3, '2026-07-27', `SHP-${baseNum - 29}`, origin, destination, km + 35, dur, 'late'),
  trip(id, 4, '2026-07-24', `SHP-${baseNum - 43}`, destination, origin, km, dur, 'completed'),
  trip(id, 5, '2026-07-21', `SHP-${baseNum - 58}`, origin, destination, km, dur, 'completed')
]

const onRouteActivity = (id: string, shipmentId: string): DriverActivityEntry[] => [
  { id: `${id}-act-1`, label: `Started trip ${shipmentId}`, at: '2026-08-03T06:15:00', via: 'Mobile App' },
  { id: `${id}-act-2`, label: 'Pre-trip inspection completed', at: '2026-08-03T05:52:00', via: 'Mobile App' },
  { id: `${id}-act-3`, label: 'Hours-of-service break logged', at: '2026-08-02T13:40:00', via: 'Mobile App' },
  { id: `${id}-act-4`, label: 'Proof of Delivery uploaded', at: '2026-08-02T16:28:00', via: 'Mobile App' },
  { id: `${id}-act-5`, label: 'Completed trip and returned to hub', at: '2026-08-01T18:10:00', via: 'Mobile App' }
]

const idleActivity = (id: string): DriverActivityEntry[] => [
  { id: `${id}-act-1`, label: 'Availability updated in driver app', at: '2026-08-02T09:05:00', via: 'Mobile App' },
  { id: `${id}-act-2`, label: 'Signed out at end of shift', at: '2026-08-01T17:30:00', via: 'Mobile App' },
  { id: `${id}-act-3`, label: 'Proof of Delivery uploaded', at: '2026-08-01T15:12:00', via: 'Mobile App' },
  { id: `${id}-act-4`, label: 'Pre-trip inspection completed', at: '2026-08-01T06:40:00', via: 'Mobile App' }
]

const authored: Driver[] = [
  {
    id: 'drv-001',
    name: 'Eddie Wang',
    initials: 'EW',
    status: 'available',
    employmentStatus: 'on_break',
    avatarUrl: '/images/avatars/avatar-1.webp',
    firstName: 'Eddie',
    lastName: 'Wang',
    dob: '1988-03-12',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2018-06-01',
    phone: '+1 (602) 555-4021',
    email: 'eddie.wang@cargorix.com',
    address: '1420 N Central Ave',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85004',
    homeHubId: 'wh-bronx',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'per_mile',
    operatingZone: 'Southwest Region',
    safetyScore: 91,
    employeeId: 'EMP-1001',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-14',
    licenseNumber: 'CDL-A 8892017',
    licenseClass: 'class_a',
    licenseState: 'AZ',
    licenseExpiry: '2028-04-18',
    endorsements: ['Tanker'],
    medicalCardExpiry: '2026-09-12',
    drugTestDue: '2027-02-10',
    availabilityNote: 'Back on duty at 2 PM',
    emergencyContact: {
      name: 'Linda Wang',
      relationship: 'Spouse',
      phone: '+1 (602) 555-8830',
      altPhone: '+1 (602) 555-8831'
    },
    documents: buildDocs(1, 'CDL-A 8892017', '2028-04-18', '2026-09-12', '2027-02-10'),
    activity: idleActivity('drv-001')
  },
  {
    id: 'drv-002',
    name: 'Maya Chen',
    initials: 'MC',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-2.webp',
    firstName: 'Maya',
    lastName: 'Chen',
    dob: '1990-07-08',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2019-02-11',
    phone: '+1 (214) 555-3092',
    email: 'maya.chen@cargorix.com',
    address: '815 Cadiz St',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    homeHubId: 'wh-newark',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'per_mile',
    operatingZone: 'South Central',
    safetyScore: 95,
    employeeId: 'EMP-1002',
    weeklyOff: 'Saturday',
    nextOff: '2026-08-20',
    licenseNumber: 'CDL-A 8814562',
    licenseClass: 'class_a',
    licenseState: 'TX',
    licenseExpiry: '2029-01-22',
    endorsements: ['HAZMAT'],
    medicalCardExpiry: '2027-05-30',
    drugTestDue: '2027-03-15',
    emergencyContact: { name: 'David Chen', relationship: 'Spouse', phone: '+1 (214) 555-6641' },
    assignedVehicle: {
      vehicleId: 'VAN-014',
      vehicleNo: 'VAN-014',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2022,
      capacityLabel: '2.5 Ton',
      registrationDate: '2022-03-10'
    },
    currentAssignment: {
      routeId: 'RTE-1041',
      routeName: 'Dallas, TX → Houston, TX',
      shipmentId: 'SHP-77801',
      cargo: 'Consumer electronics – 8 pallets',
      origin: 'Dallas, TX',
      originAddress: '1200 Cadiz St, Dallas, TX 75201',
      destination: 'Houston, TX',
      destinationAddress: '4500 Navigation Blvd, Houston, TX 77011',
      nextStop: 'Madisonville, TX',
      nextStopDistance: '58 km away',
      etaLabel: 'Today, 2:30 PM'
    },
    tripHistory: buildTrips('drv-002', 'Dallas, TX', 'Houston, TX', 385, '4h 30m', 77781),
    documents: buildDocs(2, 'CDL-A 8814562', '2029-01-22', '2027-05-30', '2027-03-15'),
    notes: 'Consistently high on-time rate on the Dallas–Houston lane. Preferred for time-critical electronics runs.',
    notesUpdatedBy: 'Sandra Mills',
    notesUpdatedAt: '2026-07-28',
    activity: onRouteActivity('drv-002', 'SHP-77801')
  },
  {
    id: 'drv-003',
    name: 'Riley Kim',
    initials: 'RK',
    status: 'available',
    employmentStatus: 'unavailable',
    avatarUrl: '/images/avatars/avatar-4.webp',
    firstName: 'Riley',
    lastName: 'Kim',
    dob: '1993-11-20',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2020-09-15',
    phone: '+1 (312) 555-7714',
    email: 'riley.kim@cargorix.com',
    address: '233 S Wacker Dr',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    homeHubId: 'wh-brooklyn',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'local',
    homeTime: 'daily',
    payType: 'hourly',
    operatingZone: 'Midwest',
    safetyScore: 88,
    employeeId: 'EMP-1003',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-24',
    licenseNumber: 'CDL-B 8720934',
    licenseClass: 'class_b',
    licenseState: 'IL',
    licenseExpiry: '2026-08-30',
    endorsements: [],
    medicalCardExpiry: '2027-06-15',
    drugTestDue: '2027-04-01',
    availabilityNote: 'Vacation approved',
    emergencyContact: { name: 'Susan Kim', relationship: 'Parent', phone: '+1 (312) 555-1180' },
    documents: buildDocs(3, 'CDL-B 8720934', '2026-08-30', '2027-06-15', '2027-04-01'),
    activity: idleActivity('drv-003')
  },
  {
    id: 'drv-004',
    name: 'Jordan Lee',
    initials: 'JL',
    status: 'offline',
    employmentStatus: 'inactive',
    avatarUrl: '/images/avatars/avatar-3.webp',
    firstName: 'Jordan',
    lastName: 'Lee',
    dob: '1985-05-03',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2016-04-22',
    phone: '+1 (404) 555-2265',
    email: 'jordan.lee@cargorix.com',
    address: '600 Peachtree St NE',
    city: 'Atlanta',
    state: 'GA',
    zip: '30303',
    homeHubId: 'wh-queens',
    shift: 'night',
    shiftHours: '6 PM – 6 AM',
    driverType: 'otr',
    homeTime: 'biweekly',
    payType: 'per_mile',
    operatingZone: 'Southeast',
    safetyScore: 82,
    employeeId: 'EMP-1004',
    weeklyOff: 'Wednesday',
    nextOff: '2026-08-10',
    licenseNumber: 'CDL-A 8603481',
    licenseClass: 'class_a',
    licenseState: 'GA',
    licenseExpiry: '2026-06-20',
    endorsements: ['HAZMAT', 'Tanker'],
    medicalCardExpiry: '2027-01-10',
    drugTestDue: '2026-12-05',
    availabilityNote: 'Medical leave',
    emergencyContact: { name: 'Michelle Lee', relationship: 'Spouse', phone: '+1 (404) 555-9903' },
    documents: buildDocs(4, 'CDL-A 8603481', '2026-06-20', '2027-01-10', '2026-12-05'),
    activity: idleActivity('drv-004')
  },
  {
    id: 'drv-005',
    name: 'Ethan Brooks',
    initials: 'EB',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-5.webp',
    firstName: 'Ethan',
    lastName: 'Brooks',
    dob: '1987-09-14',
    gender: 'male',
    nationality: 'American',
    languages: ['English', 'Spanish'],
    hireDate: '2017-07-30',
    phone: '+1 (303) 555-4417',
    email: 'ethan.brooks@cargorix.com',
    address: '1701 Wynkoop St',
    city: 'Denver',
    state: 'CO',
    zip: '80202',
    homeHubId: 'wh-bronx',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'otr',
    homeTime: 'weekly',
    payType: 'per_mile',
    operatingZone: 'Mountain West',
    safetyScore: 94,
    employeeId: 'EMP-1005',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-23',
    licenseNumber: 'CDL-A 8551209',
    licenseClass: 'class_a',
    licenseState: 'CO',
    licenseExpiry: '2028-10-05',
    endorsements: ['HAZMAT', 'Tanker'],
    medicalCardExpiry: '2027-08-19',
    drugTestDue: '2027-06-12',
    emergencyContact: {
      name: 'Rachel Brooks',
      relationship: 'Spouse',
      phone: '+1 (303) 555-2288',
      altPhone: '+1 (303) 555-2289'
    },
    assignedVehicle: {
      vehicleId: 'TRK-208',
      vehicleNo: 'TRK-208',
      make: 'Volvo',
      model: 'VNL 760',
      typeLabel: 'Truck (Container)',
      year: 2021,
      capacityLabel: '20 Ton',
      registrationDate: '2021-06-15'
    },
    currentAssignment: {
      routeId: 'RTE-1044',
      routeName: 'Denver, CO → Salt Lake City, UT',
      shipmentId: 'SHP-77804',
      cargo: 'Building materials – 14 pallets',
      origin: 'Denver, CO',
      originAddress: '1701 Wynkoop St, Denver, CO 80202',
      destination: 'Salt Lake City, UT',
      destinationAddress: '350 S 400 W, Salt Lake City, UT 84101',
      nextStop: 'Grand Junction, CO',
      nextStopDistance: '120 km away',
      etaLabel: 'Today, 5:15 PM'
    },
    tripHistory: buildTrips('drv-005', 'Denver, CO', 'Salt Lake City, UT', 600, '7h 40m', 77784),
    documents: buildDocs(5, 'CDL-A 8551209', '2028-10-05', '2027-08-19', '2027-06-12'),
    notes: 'HAZMAT-certified long-haul driver. Reliable on mountain grades and winter routes.',
    notesUpdatedBy: 'Marcus Reyes',
    notesUpdatedAt: '2026-07-30',
    activity: onRouteActivity('drv-005', 'SHP-77804')
  },
  {
    id: 'drv-006',
    name: 'Olivia Reed',
    initials: 'OR',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-6.webp',
    firstName: 'Olivia',
    lastName: 'Reed',
    dob: '1991-12-01',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2019-05-06',
    phone: '+1 (813) 555-6690',
    email: 'olivia.reed@cargorix.com',
    address: '401 E Jackson St',
    city: 'Tampa',
    state: 'FL',
    zip: '33602',
    homeHubId: 'wh-newark',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'salary',
    operatingZone: 'Gulf Coast',
    safetyScore: 90,
    employeeId: 'EMP-1006',
    weeklyOff: 'Saturday',
    nextOff: '2026-08-29',
    licenseNumber: 'CDL-A 8478153',
    licenseClass: 'class_a',
    licenseState: 'FL',
    licenseExpiry: '2026-09-30',
    endorsements: ['Doubles/Triples'],
    medicalCardExpiry: '2027-03-22',
    drugTestDue: '2027-01-18',
    emergencyContact: { name: 'Mark Reed', relationship: 'Spouse', phone: '+1 (813) 555-7712' },
    assignedVehicle: {
      vehicleId: 'TRK-115',
      vehicleNo: 'TRK-115',
      make: 'Freightliner',
      model: 'Cascadia',
      typeLabel: 'Truck (Container)',
      year: 2020,
      capacityLabel: '22 Ton',
      registrationDate: '2020-09-02'
    },
    currentAssignment: {
      routeId: 'RTE-1045',
      routeName: 'Tampa, FL → Miami, FL',
      shipmentId: 'SHP-77805',
      cargo: 'Packaged beverages – 18 pallets',
      origin: 'Tampa, FL',
      destination: 'Miami, FL',
      destinationAddress: '2100 NW 21st St, Miami, FL 33142',
      nextStop: 'Fort Myers, FL',
      nextStopDistance: '75 km away',
      etaLabel: 'Today, 1:45 PM'
    },
    tripHistory: buildTrips('drv-006', 'Tampa, FL', 'Miami, FL', 450, '4h 15m', 77785),
    documents: buildDocs(6, 'CDL-A 8478153', '2026-09-30', '2027-03-22', '2027-01-18'),
    activity: onRouteActivity('drv-006', 'SHP-77805')
  },
  {
    id: 'drv-007',
    name: 'Sophia Turner',
    initials: 'ST',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-8.webp',
    firstName: 'Sophia',
    lastName: 'Turner',
    dob: '1992-02-17',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2020-01-20',
    phone: '+1 (206) 555-3348',
    email: 'sophia.turner@cargorix.com',
    address: '1301 5th Ave',
    city: 'Seattle',
    state: 'WA',
    zip: '98101',
    homeHubId: 'wh-brooklyn',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'hourly',
    operatingZone: 'Pacific Northwest',
    safetyScore: 92,
    employeeId: 'EMP-1007',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-27',
    licenseNumber: 'CDL-A 8390477',
    licenseClass: 'class_a',
    licenseState: 'WA',
    licenseExpiry: '2028-07-14',
    endorsements: [],
    medicalCardExpiry: '2027-04-09',
    drugTestDue: '2027-02-25',
    emergencyContact: { name: 'James Turner', relationship: 'Parent', phone: '+1 (206) 555-9021' },
    assignedVehicle: {
      vehicleId: 'VAN-101',
      vehicleNo: 'VAN-101',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2023,
      capacityLabel: '2.5 Ton',
      registrationDate: '2023-01-20'
    },
    currentAssignment: {
      routeId: 'RTE-1046',
      routeName: 'Seattle, WA → Portland, OR',
      shipmentId: 'SHP-77806',
      cargo: 'Retail apparel – 6 pallets',
      origin: 'Seattle, WA',
      destination: 'Portland, OR',
      nextStop: 'Tacoma, WA',
      nextStopDistance: '42 km away',
      etaLabel: 'Today, 11:30 AM'
    },
    tripHistory: buildTrips('drv-007', 'Seattle, WA', 'Portland, OR', 280, '3h 10m', 77786),
    documents: buildDocs(7, 'CDL-A 8390477', '2028-07-14', '2027-04-09', '2027-02-25'),
    activity: onRouteActivity('drv-007', 'SHP-77806')
  },
  {
    id: 'drv-008',
    name: 'Marcus Bennett',
    initials: 'MB',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-7.webp',
    firstName: 'Marcus',
    lastName: 'Bennett',
    dob: '1986-08-25',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2016-11-14',
    phone: '+1 (201) 555-5573',
    email: 'marcus.bennett@cargorix.com',
    address: '2 Riverfront Plaza',
    city: 'Newark',
    state: 'NJ',
    zip: '07102',
    homeHubId: 'wh-newark',
    shift: 'night',
    shiftHours: '6 PM – 6 AM',
    driverType: 'otr',
    homeTime: 'biweekly',
    payType: 'per_mile',
    operatingZone: 'Northeast Corridor',
    safetyScore: 89,
    employeeId: 'EMP-1008',
    weeklyOff: 'Monday',
    nextOff: '2026-08-18',
    licenseNumber: 'CDL-A 8267340',
    licenseClass: 'class_a',
    licenseState: 'NJ',
    licenseExpiry: '2029-03-11',
    endorsements: ['HAZMAT', 'Tanker'],
    medicalCardExpiry: '2027-07-08',
    drugTestDue: '2027-05-19',
    emergencyContact: { name: 'Angela Bennett', relationship: 'Spouse', phone: '+1 (201) 555-4406' },
    assignedVehicle: {
      vehicleId: 'TRK-301',
      vehicleNo: 'TRK-301',
      make: 'International',
      model: 'LT Series',
      typeLabel: 'Truck (Reefer)',
      year: 2021,
      capacityLabel: '18 Ton',
      registrationDate: '2021-11-11'
    },
    currentAssignment: {
      routeId: 'RTE-1047',
      routeName: 'Newark, NJ → Boston, MA',
      shipmentId: 'SHP-77807',
      cargo: 'Refrigerated dairy – 12 pallets',
      origin: 'Newark, NJ',
      destination: 'Boston, MA',
      destinationAddress: '100 Cambridge St, Boston, MA 02114',
      nextStop: 'Hartford, CT',
      nextStopDistance: '95 km away',
      etaLabel: 'Today, 6:00 PM'
    },
    tripHistory: buildTrips('drv-008', 'Newark, NJ', 'Boston, MA', 350, '4h 5m', 77787),
    documents: buildDocs(8, 'CDL-A 8267340', '2029-03-11', '2027-07-08', '2027-05-19'),
    notes: 'Reefer specialist for the Northeast dairy contract. Monitors temperature logs meticulously.',
    notesUpdatedBy: 'Denise Faulkner',
    notesUpdatedAt: '2026-07-25',
    activity: onRouteActivity('drv-008', 'SHP-77807')
  },
  {
    id: 'drv-009',
    name: 'Emma Collins',
    initials: 'EC',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-10.webp',
    firstName: 'Emma',
    lastName: 'Collins',
    dob: '1994-04-11',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2021-03-08',
    phone: '+1 (503) 555-6135',
    email: 'emma.collins@cargorix.com',
    address: '1120 SW 5th Ave',
    city: 'Portland',
    state: 'OR',
    zip: '97201',
    homeHubId: 'wh-queens',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'otr',
    homeTime: 'weekly',
    payType: 'per_mile',
    operatingZone: 'Pacific Northwest',
    safetyScore: 96,
    employeeId: 'EMP-1009',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-30',
    licenseNumber: 'CDL-A 8123098',
    licenseClass: 'class_a',
    licenseState: 'OR',
    licenseExpiry: '2028-05-27',
    endorsements: ['Tanker'],
    medicalCardExpiry: '2027-09-30',
    drugTestDue: '2027-08-02',
    emergencyContact: { name: 'Robert Collins', relationship: 'Parent', phone: '+1 (503) 555-8874' },
    assignedVehicle: {
      vehicleId: 'VAN-102',
      vehicleNo: 'VAN-102',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2022,
      capacityLabel: '2.5 Ton',
      registrationDate: '2022-05-18'
    },
    currentAssignment: {
      routeId: 'RTE-1048',
      routeName: 'Portland, OR → Sacramento, CA',
      shipmentId: 'SHP-77808',
      cargo: 'Industrial parts – 10 pallets',
      origin: 'Portland, OR',
      destination: 'Sacramento, CA',
      nextStop: 'Medford, OR',
      nextStopDistance: '150 km away',
      etaLabel: 'Tomorrow, 8:20 AM'
    },
    tripHistory: buildTrips('drv-009', 'Portland, OR', 'Sacramento, CA', 930, '9h 20m', 77788),
    documents: buildDocs(9, 'CDL-A 8123098', '2028-05-27', '2027-09-30', '2027-08-02'),
    activity: onRouteActivity('drv-009', 'SHP-77808')
  },
  {
    id: 'drv-010',
    name: 'Ryan Cooper',
    initials: 'RC',
    status: 'on_route',
    employmentStatus: 'on_break',
    avatarUrl: '/images/avatars/avatar-9.webp',
    firstName: 'Ryan',
    lastName: 'Cooper',
    dob: '1995-06-30',
    gender: 'male',
    nationality: 'American',
    languages: ['English', 'Spanish'],
    hireDate: '2021-10-01',
    phone: '+1 (602) 555-7788',
    email: 'ryan.cooper@cargorix.com',
    address: '2201 E Camelback Rd',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85008',
    homeHubId: 'wh-bronx',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'local',
    homeTime: 'daily',
    payType: 'hourly',
    operatingZone: 'Southwest Region',
    safetyScore: 85,
    employeeId: 'EMP-1010',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-15',
    licenseNumber: 'CDL-B 8055271',
    licenseClass: 'class_b',
    licenseState: 'AZ',
    licenseExpiry: '2028-02-19',
    endorsements: [],
    medicalCardExpiry: '2026-08-22',
    drugTestDue: '2027-01-05',
    availabilityNote: 'On DOT-mandated break',
    emergencyContact: { name: 'Jessica Cooper', relationship: 'Sibling', phone: '+1 (602) 555-1145' },
    assignedVehicle: {
      vehicleId: 'BIKE-029',
      vehicleNo: 'BIKE-029',
      make: 'Ford',
      model: 'Transit',
      typeLabel: 'Cargo Van',
      year: 2023,
      capacityLabel: '1 Ton',
      registrationDate: '2023-04-05'
    },
    currentAssignment: {
      routeId: 'RTE-1049',
      routeName: 'Phoenix, AZ → Tucson, AZ',
      shipmentId: 'SHP-77809',
      cargo: 'Medical supplies – 3 pallets',
      origin: 'Phoenix, AZ',
      destination: 'Tucson, AZ',
      nextStop: 'Casa Grande, AZ',
      nextStopDistance: '38 km away',
      etaLabel: 'Today, 12:10 PM'
    },
    tripHistory: buildTrips('drv-010', 'Phoenix, AZ', 'Tucson, AZ', 185, '1h 55m', 77789),
    documents: buildDocs(10, 'CDL-B 8055271', '2028-02-19', '2026-08-22', '2027-01-05'),
    notes: 'Handles same-day medical courier runs. Flag medical card renewal — due within 60 days.',
    notesUpdatedBy: 'Sandra Mills',
    notesUpdatedAt: '2026-07-31',
    activity: onRouteActivity('drv-010', 'SHP-77809')
  },
  {
    id: 'drv-011',
    name: 'Ava Mitchell',
    initials: 'AM',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-12.webp',
    firstName: 'Ava',
    lastName: 'Mitchell',
    dob: '1990-10-19',
    gender: 'female',
    nationality: 'American',
    languages: ['English', 'Spanish'],
    hireDate: '2019-08-27',
    phone: '+1 (214) 555-2410',
    email: 'ava.mitchell@cargorix.com',
    address: '1409 Botham Jean Blvd',
    city: 'Dallas',
    state: 'TX',
    zip: '75204',
    homeHubId: 'wh-newark',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'per_mile',
    operatingZone: 'South Central',
    safetyScore: 93,
    employeeId: 'EMP-1011',
    weeklyOff: 'Saturday',
    nextOff: '2026-08-26',
    licenseNumber: 'CDL-A 8998762',
    licenseClass: 'class_a',
    licenseState: 'TX',
    licenseExpiry: '2029-06-04',
    endorsements: ['Doubles/Triples'],
    medicalCardExpiry: '2027-10-12',
    drugTestDue: '2027-07-21',
    emergencyContact: { name: 'Daniel Mitchell', relationship: 'Spouse', phone: '+1 (214) 555-3357' },
    assignedVehicle: {
      vehicleId: 'VAN-103',
      vehicleNo: 'VAN-103',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2022,
      capacityLabel: '2.5 Ton',
      registrationDate: '2022-08-27'
    },
    currentAssignment: {
      routeId: 'RTE-1050',
      routeName: 'Dallas, TX → Oklahoma City, OK',
      shipmentId: 'SHP-77810',
      cargo: 'Auto parts – 9 pallets',
      origin: 'Dallas, TX',
      destination: 'Oklahoma City, OK',
      nextStop: 'Ardmore, OK',
      nextStopDistance: '64 km away',
      etaLabel: 'Today, 3:20 PM'
    },
    tripHistory: buildTrips('drv-011', 'Dallas, TX', 'Oklahoma City, OK', 330, '3h 20m', 77790),
    documents: buildDocs(11, 'CDL-A 8998762', '2029-06-04', '2027-10-12', '2027-07-21'),
    activity: onRouteActivity('drv-011', 'SHP-77810')
  },
  {
    id: 'drv-012',
    name: 'Kevin Hayes',
    initials: 'KH',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-11.webp',
    firstName: 'Kevin',
    lastName: 'Hayes',
    dob: '1988-01-27',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2017-12-04',
    phone: '+1 (312) 555-8802',
    email: 'kevin.hayes@cargorix.com',
    address: '600 W Chicago Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60607',
    homeHubId: 'wh-brooklyn',
    shift: 'night',
    shiftHours: '6 PM – 6 AM',
    driverType: 'otr',
    homeTime: 'biweekly',
    payType: 'per_mile',
    operatingZone: 'Midwest',
    safetyScore: 91,
    employeeId: 'EMP-1012',
    weeklyOff: 'Tuesday',
    nextOff: '2026-08-19',
    licenseNumber: 'CDL-A 8442119',
    licenseClass: 'class_a',
    licenseState: 'IL',
    licenseExpiry: '2028-09-08',
    endorsements: ['HAZMAT', 'Tanker'],
    medicalCardExpiry: '2027-06-28',
    drugTestDue: '2027-04-14',
    emergencyContact: { name: 'Laura Hayes', relationship: 'Spouse', phone: '+1 (312) 555-6690' },
    assignedVehicle: {
      vehicleId: 'TRK-302',
      vehicleNo: 'TRK-302',
      make: 'Kenworth',
      model: 'T680',
      typeLabel: 'Truck (Reefer)',
      year: 2020,
      capacityLabel: '20 Ton',
      registrationDate: '2020-12-14'
    },
    currentAssignment: {
      routeId: 'RTE-1051',
      routeName: 'Chicago, IL → Indianapolis, IN',
      shipmentId: 'SHP-77811',
      cargo: 'Frozen foods – 15 pallets',
      origin: 'Chicago, IL',
      destination: 'Indianapolis, IN',
      nextStop: 'Lafayette, IN',
      nextStopDistance: '82 km away',
      etaLabel: 'Today, 4:00 PM'
    },
    tripHistory: buildTrips('drv-012', 'Chicago, IL', 'Indianapolis, IN', 295, '3h 5m', 77791),
    documents: buildDocs(12, 'CDL-A 8442119', '2028-09-08', '2027-06-28', '2027-04-14'),
    activity: onRouteActivity('drv-012', 'SHP-77811')
  },
  {
    id: 'drv-013',
    name: 'Mia Foster',
    initials: 'MF',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-15.webp',
    firstName: 'Mia',
    lastName: 'Foster',
    dob: '1993-03-05',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2020-06-16',
    phone: '+1 (404) 555-4478',
    email: 'mia.foster@cargorix.com',
    address: '191 Peachtree St NE',
    city: 'Atlanta',
    state: 'GA',
    zip: '30308',
    homeHubId: 'wh-queens',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'salary',
    operatingZone: 'Southeast',
    safetyScore: 90,
    employeeId: 'EMP-1013',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-28',
    licenseNumber: 'CDL-A 8710654',
    licenseClass: 'class_a',
    licenseState: 'GA',
    licenseExpiry: '2028-12-15',
    endorsements: ['Tanker'],
    medicalCardExpiry: '2026-09-28',
    drugTestDue: '2027-03-30',
    emergencyContact: { name: 'Thomas Foster', relationship: 'Parent', phone: '+1 (404) 555-2231' },
    assignedVehicle: {
      vehicleId: 'VAN-104',
      vehicleNo: 'VAN-104',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2023,
      capacityLabel: '2.5 Ton',
      registrationDate: '2023-06-16'
    },
    currentAssignment: {
      routeId: 'RTE-1052',
      routeName: 'Atlanta, GA → Charlotte, NC',
      shipmentId: 'SHP-77812',
      cargo: 'Consumer goods – 7 pallets',
      origin: 'Atlanta, GA',
      destination: 'Charlotte, NC',
      nextStop: 'Greenville, SC',
      nextStopDistance: '70 km away',
      etaLabel: 'Today, 2:15 PM'
    },
    tripHistory: buildTrips('drv-013', 'Atlanta, GA', 'Charlotte, NC', 395, '3h 50m', 77792),
    documents: buildDocs(13, 'CDL-A 8710654', '2028-12-15', '2026-09-28', '2027-03-30'),
    notes: 'Medical card expiring within 60 days — schedule DOT physical before next long assignment.',
    notesUpdatedBy: 'Denise Faulkner',
    notesUpdatedAt: '2026-08-01',
    activity: onRouteActivity('drv-013', 'SHP-77812')
  },
  {
    id: 'drv-014',
    name: 'Daniel Reed',
    initials: 'DR',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-13.webp',
    firstName: 'Daniel',
    lastName: 'Reed',
    dob: '1996-07-22',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2022-02-10',
    phone: '+1 (303) 555-9964',
    email: 'daniel.reed@cargorix.com',
    address: '1550 Wewatta St',
    city: 'Denver',
    state: 'CO',
    zip: '80205',
    homeHubId: 'wh-bronx',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'local',
    homeTime: 'daily',
    payType: 'hourly',
    operatingZone: 'Mountain West',
    safetyScore: 87,
    employeeId: 'EMP-1014',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-21',
    licenseNumber: 'CDL-A 8331046',
    licenseClass: 'class_a',
    licenseState: 'CO',
    licenseExpiry: '2029-02-27',
    endorsements: [],
    medicalCardExpiry: '2027-11-19',
    drugTestDue: '2027-09-08',
    emergencyContact: { name: 'Karen Reed', relationship: 'Parent', phone: '+1 (303) 555-3390' },
    assignedVehicle: {
      vehicleId: 'BIKE-030',
      vehicleNo: 'BIKE-030',
      make: 'Ford',
      model: 'Transit',
      typeLabel: 'Cargo Van',
      year: 2023,
      capacityLabel: '1 Ton',
      registrationDate: '2023-02-10'
    },
    currentAssignment: {
      routeId: 'RTE-1053',
      routeName: 'Denver, CO → Colorado Springs, CO',
      shipmentId: 'SHP-77813',
      cargo: 'Courier parcels – 2 pallets',
      origin: 'Denver, CO',
      destination: 'Colorado Springs, CO',
      nextStop: 'Castle Rock, CO',
      nextStopDistance: '32 km away',
      etaLabel: 'Today, 10:40 AM'
    },
    tripHistory: buildTrips('drv-014', 'Denver, CO', 'Colorado Springs, CO', 110, '1h 20m', 77793),
    documents: buildDocs(14, 'CDL-A 8331046', '2029-02-27', '2027-11-19', '2027-09-08'),
    activity: onRouteActivity('drv-014', 'SHP-77813')
  },
  {
    id: 'drv-015',
    name: 'Lily Bennett',
    initials: 'LB',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-16.webp',
    firstName: 'Lily',
    lastName: 'Bennett',
    dob: '1991-09-09',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2019-11-25',
    phone: '+1 (813) 555-2274',
    email: 'lily.bennett@cargorix.com',
    address: '777 N Ashley Dr',
    city: 'Tampa',
    state: 'FL',
    zip: '33607',
    homeHubId: 'wh-newark',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'hourly',
    operatingZone: 'Gulf Coast',
    safetyScore: 92,
    employeeId: 'EMP-1015',
    weeklyOff: 'Saturday',
    nextOff: '2026-08-25',
    licenseNumber: 'CDL-A 8620418',
    licenseClass: 'class_a',
    licenseState: 'FL',
    licenseExpiry: '2028-08-30',
    endorsements: ['Doubles/Triples'],
    medicalCardExpiry: '2027-05-14',
    drugTestDue: '2027-02-06',
    emergencyContact: { name: 'Paul Bennett', relationship: 'Spouse', phone: '+1 (813) 555-8817' },
    assignedVehicle: {
      vehicleId: 'VAN-105',
      vehicleNo: 'VAN-105',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2022,
      capacityLabel: '2.5 Ton',
      registrationDate: '2022-11-25'
    },
    currentAssignment: {
      routeId: 'RTE-1054',
      routeName: 'Tampa, FL → Orlando, FL',
      shipmentId: 'SHP-77814',
      cargo: 'Retail electronics – 5 pallets',
      origin: 'Tampa, FL',
      destination: 'Orlando, FL',
      nextStop: 'Lakeland, FL',
      nextStopDistance: '48 km away',
      etaLabel: 'Today, 11:55 AM'
    },
    tripHistory: buildTrips('drv-015', 'Tampa, FL', 'Orlando, FL', 135, '1h 35m', 77794),
    documents: buildDocs(15, 'CDL-A 8620418', '2028-08-30', '2027-05-14', '2027-02-06'),
    activity: onRouteActivity('drv-015', 'SHP-77814')
  },
  {
    id: 'drv-016',
    name: 'Bryan Cole',
    initials: 'BC',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-14.webp',
    firstName: 'Bryan',
    lastName: 'Cole',
    dob: '1987-11-13',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2017-05-19',
    phone: '+1 (206) 555-4409',
    email: 'bryan.cole@cargorix.com',
    address: '2200 Westlake Ave',
    city: 'Seattle',
    state: 'WA',
    zip: '98109',
    homeHubId: 'wh-brooklyn',
    shift: 'night',
    shiftHours: '6 PM – 6 AM',
    driverType: 'otr',
    homeTime: 'biweekly',
    payType: 'per_mile',
    operatingZone: 'Pacific Northwest',
    safetyScore: 88,
    employeeId: 'EMP-1016',
    weeklyOff: 'Monday',
    nextOff: '2026-08-17',
    licenseNumber: 'CDL-A 8204873',
    licenseClass: 'class_a',
    licenseState: 'WA',
    licenseExpiry: '2029-04-16',
    endorsements: ['HAZMAT', 'Tanker'],
    medicalCardExpiry: '2027-08-27',
    drugTestDue: '2027-06-30',
    emergencyContact: { name: 'Nicole Cole', relationship: 'Spouse', phone: '+1 (206) 555-6628' },
    assignedVehicle: {
      vehicleId: 'TRK-303',
      vehicleNo: 'TRK-303',
      make: 'Peterbilt',
      model: '579',
      typeLabel: 'Truck (Reefer)',
      year: 2021,
      capacityLabel: '19 Ton',
      registrationDate: '2021-05-19'
    },
    currentAssignment: {
      routeId: 'RTE-1055',
      routeName: 'Seattle, WA → Spokane, WA',
      shipmentId: 'SHP-77815',
      cargo: 'Refrigerated produce – 13 pallets',
      origin: 'Seattle, WA',
      destination: 'Spokane, WA',
      nextStop: 'Ellensburg, WA',
      nextStopDistance: '88 km away',
      etaLabel: 'Today, 4:20 PM'
    },
    tripHistory: buildTrips('drv-016', 'Seattle, WA', 'Spokane, WA', 440, '4h 20m', 77795),
    documents: buildDocs(16, 'CDL-A 8204873', '2029-04-16', '2027-08-27', '2027-06-30'),
    activity: onRouteActivity('drv-016', 'SHP-77815')
  },
  {
    id: 'drv-017',
    name: 'Chloe Parker',
    initials: 'CP',
    status: 'on_route',
    employmentStatus: 'on_break',
    avatarUrl: '/images/avatars/avatar-18.webp',
    firstName: 'Chloe',
    lastName: 'Parker',
    dob: '1994-12-28',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2021-07-12',
    phone: '+1 (201) 555-3316',
    email: 'chloe.parker@cargorix.com',
    address: '55 Washington St',
    city: 'Newark',
    state: 'NJ',
    zip: '07105',
    homeHubId: 'wh-newark',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'local',
    homeTime: 'daily',
    payType: 'hourly',
    operatingZone: 'Northeast Corridor',
    safetyScore: 86,
    employeeId: 'EMP-1017',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-13',
    licenseNumber: 'CDL-A 8087652',
    licenseClass: 'class_a',
    licenseState: 'NJ',
    licenseExpiry: '2026-09-26',
    endorsements: [],
    medicalCardExpiry: '2027-04-22',
    drugTestDue: '2027-01-30',
    availabilityNote: 'On DOT-mandated break',
    emergencyContact: { name: 'Steven Parker', relationship: 'Parent', phone: '+1 (201) 555-7743' },
    assignedVehicle: {
      vehicleId: 'VAN-106',
      vehicleNo: 'VAN-106',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2023,
      capacityLabel: '2.5 Ton',
      registrationDate: '2023-07-12'
    },
    currentAssignment: {
      routeId: 'RTE-1056',
      routeName: 'Newark, NJ → Philadelphia, PA',
      shipmentId: 'SHP-77816',
      cargo: 'Packaged goods – 6 pallets',
      origin: 'Newark, NJ',
      destination: 'Philadelphia, PA',
      nextStop: 'Trenton, NJ',
      nextStopDistance: '35 km away',
      etaLabel: 'Today, 12:50 PM'
    },
    tripHistory: buildTrips('drv-017', 'Newark, NJ', 'Philadelphia, PA', 150, '1h 50m', 77796),
    documents: buildDocs(17, 'CDL-A 8087652', '2026-09-26', '2027-04-22', '2027-01-30'),
    activity: onRouteActivity('drv-017', 'SHP-77816')
  },
  {
    id: 'drv-018',
    name: 'Nathan Ward',
    initials: 'NW',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-17.webp',
    firstName: 'Nathan',
    lastName: 'Ward',
    dob: '1989-04-06',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2018-09-17',
    phone: '+1 (503) 555-5521',
    email: 'nathan.ward@cargorix.com',
    address: '1000 SW Broadway',
    city: 'Portland',
    state: 'OR',
    zip: '97205',
    homeHubId: 'wh-queens',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'salary',
    operatingZone: 'Pacific Northwest',
    safetyScore: 91,
    employeeId: 'EMP-1018',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-24',
    licenseNumber: 'CDL-A 8560237',
    licenseClass: 'class_a',
    licenseState: 'OR',
    licenseExpiry: '2028-11-02',
    endorsements: ['Tanker'],
    medicalCardExpiry: '2027-07-31',
    drugTestDue: '2027-05-08',
    emergencyContact: { name: 'Emily Ward', relationship: 'Spouse', phone: '+1 (503) 555-9938' },
    assignedVehicle: {
      vehicleId: 'VAN-107',
      vehicleNo: 'VAN-107',
      make: 'Mercedes-Benz',
      model: 'Sprinter',
      typeLabel: 'Cargo Van',
      year: 2022,
      capacityLabel: '2.5 Ton',
      registrationDate: '2022-09-17'
    },
    currentAssignment: {
      routeId: 'RTE-1057',
      routeName: 'Portland, OR → Eugene, OR',
      shipmentId: 'SHP-77817',
      cargo: 'Furniture – 4 pallets',
      origin: 'Portland, OR',
      destination: 'Eugene, OR',
      nextStop: 'Salem, OR',
      nextStopDistance: '45 km away',
      etaLabel: 'Today, 1:05 PM'
    },
    tripHistory: buildTrips('drv-018', 'Portland, OR', 'Eugene, OR', 180, '1h 55m', 77797),
    documents: buildDocs(18, 'CDL-A 8560237', '2028-11-02', '2027-07-31', '2027-05-08'),
    activity: onRouteActivity('drv-018', 'SHP-77817')
  },
  {
    id: 'drv-019',
    name: 'Owen Hayes',
    initials: 'OH',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-19.webp',
    firstName: 'Owen',
    lastName: 'Hayes',
    dob: '1986-02-19',
    gender: 'male',
    nationality: 'American',
    languages: ['English', 'Spanish'],
    hireDate: '2016-08-08',
    phone: '+1 (602) 555-6674',
    email: 'owen.hayes@cargorix.com',
    address: '100 W Washington St',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85012',
    homeHubId: 'wh-bronx',
    shift: 'night',
    shiftHours: '6 PM – 6 AM',
    driverType: 'otr',
    homeTime: 'biweekly',
    payType: 'per_mile',
    operatingZone: 'Southwest Region',
    safetyScore: 94,
    employeeId: 'EMP-1019',
    weeklyOff: 'Wednesday',
    nextOff: '2026-08-22',
    licenseNumber: 'CDL-A 8149920',
    licenseClass: 'class_a',
    licenseState: 'AZ',
    licenseExpiry: '2029-05-20',
    endorsements: ['HAZMAT', 'Tanker', 'Doubles/Triples'],
    medicalCardExpiry: '2027-09-13',
    drugTestDue: '2027-08-15',
    emergencyContact: {
      name: 'Grace Hayes',
      relationship: 'Spouse',
      phone: '+1 (602) 555-2204',
      altPhone: '+1 (602) 555-2205'
    },
    assignedVehicle: {
      vehicleId: 'TRK-304',
      vehicleNo: 'TRK-304',
      make: 'International',
      model: 'LT Series',
      typeLabel: 'Truck (Container)',
      year: 2021,
      capacityLabel: '21 Ton',
      registrationDate: '2021-08-08'
    },
    currentAssignment: {
      routeId: 'RTE-1058',
      routeName: 'Phoenix, AZ → Los Angeles, CA',
      shipmentId: 'SHP-77818',
      cargo: 'Container freight – 16 pallets',
      origin: 'Phoenix, AZ',
      originAddress: '100 W Washington St, Phoenix, AZ 85012',
      destination: 'Los Angeles, CA',
      destinationAddress: '2200 E 15th St, Los Angeles, CA 90021',
      nextStop: 'Blythe, CA',
      nextStopDistance: '110 km away',
      etaLabel: 'Today, 7:30 PM'
    },
    tripHistory: buildTrips('drv-019', 'Phoenix, AZ', 'Los Angeles, CA', 600, '5h 45m', 77798),
    documents: buildDocs(19, 'CDL-A 8149920', '2029-05-20', '2027-09-13', '2027-08-15'),
    notes: 'Top safety score on the fleet. Preferred lead driver for the Phoenix–LA container corridor.',
    notesUpdatedBy: 'Marcus Reyes',
    notesUpdatedAt: '2026-08-02',
    activity: onRouteActivity('drv-019', 'SHP-77818')
  },
  {
    id: 'drv-020',
    name: 'Grace Morgan',
    initials: 'GM',
    status: 'on_route',
    employmentStatus: 'active',
    avatarUrl: '/images/avatars/avatar-20.webp',
    firstName: 'Grace',
    lastName: 'Morgan',
    dob: '1995-08-14',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2021-12-02',
    phone: '+1 (214) 555-8840',
    email: 'grace.morgan@cargorix.com',
    address: '2323 N Houston St',
    city: 'Dallas',
    state: 'TX',
    zip: '75207',
    homeHubId: 'wh-newark',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'local',
    homeTime: 'daily',
    payType: 'hourly',
    operatingZone: 'South Central',
    safetyScore: 89,
    employeeId: 'EMP-1020',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-16',
    licenseNumber: 'CDL-B 8038571',
    licenseClass: 'class_b',
    licenseState: 'TX',
    licenseExpiry: '2028-06-11',
    endorsements: [],
    medicalCardExpiry: '2027-06-04',
    drugTestDue: '2027-03-11',
    emergencyContact: { name: 'Peter Morgan', relationship: 'Parent', phone: '+1 (214) 555-4451' },
    assignedVehicle: {
      vehicleId: 'BIKE-031',
      vehicleNo: 'BIKE-031',
      make: 'Ford',
      model: 'Transit',
      typeLabel: 'Cargo Van',
      year: 2023,
      capacityLabel: '1 Ton',
      registrationDate: '2023-12-02'
    },
    currentAssignment: {
      routeId: 'RTE-1059',
      routeName: 'Dallas, TX → Austin, TX',
      shipmentId: 'SHP-77819',
      cargo: 'Courier parcels – 3 pallets',
      origin: 'Dallas, TX',
      destination: 'Austin, TX',
      nextStop: 'Waco, TX',
      nextStopDistance: '52 km away',
      etaLabel: 'Today, 12:30 PM'
    },
    tripHistory: buildTrips('drv-020', 'Dallas, TX', 'Austin, TX', 315, '3h 0m', 77799),
    documents: buildDocs(20, 'CDL-B 8038571', '2028-06-11', '2027-06-04', '2027-03-11'),
    activity: onRouteActivity('drv-020', 'SHP-77819')
  },
  {
    id: 'drv-021',
    name: 'Lucas Ward',
    initials: 'LW',
    status: 'available',
    employmentStatus: 'on_break',
    avatarUrl: '/images/avatars/avatar-1.webp',
    firstName: 'Lucas',
    lastName: 'Ward',
    dob: '1990-05-24',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2019-04-15',
    phone: '+1 (312) 555-2298',
    email: 'lucas.ward@cargorix.com',
    address: '540 N Michigan Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60610',
    homeHubId: 'wh-brooklyn',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'per_mile',
    operatingZone: 'Midwest',
    safetyScore: 90,
    employeeId: 'EMP-1021',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-12',
    licenseNumber: 'CDL-A 8471263',
    licenseClass: 'class_a',
    licenseState: 'IL',
    licenseExpiry: '2028-10-28',
    endorsements: ['Tanker'],
    medicalCardExpiry: '2027-10-05',
    drugTestDue: '2027-07-27',
    availabilityNote: 'On lunch break',
    emergencyContact: { name: 'Sarah Ward', relationship: 'Spouse', phone: '+1 (312) 555-6617' },
    documents: buildDocs(21, 'CDL-A 8471263', '2028-10-28', '2027-10-05', '2027-07-27'),
    activity: idleActivity('drv-021')
  },
  {
    id: 'drv-022',
    name: 'Samuel Brooks',
    initials: 'SB',
    status: 'available',
    employmentStatus: 'unavailable',
    avatarUrl: '/images/avatars/avatar-3.webp',
    firstName: 'Samuel',
    lastName: 'Brooks',
    dob: '1984-10-30',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2015-06-09',
    phone: '+1 (404) 555-3370',
    email: 'samuel.brooks@cargorix.com',
    address: '235 Peachtree St NE',
    city: 'Atlanta',
    state: 'GA',
    zip: '30312',
    homeHubId: 'wh-queens',
    shift: 'night',
    shiftHours: '6 PM – 6 AM',
    driverType: 'otr',
    homeTime: 'biweekly',
    payType: 'per_mile',
    operatingZone: 'Southeast',
    safetyScore: 83,
    employeeId: 'EMP-1022',
    weeklyOff: 'Thursday',
    nextOff: '2026-08-11',
    licenseNumber: 'CDL-A 8629014',
    licenseClass: 'class_a',
    licenseState: 'GA',
    licenseExpiry: '2026-09-18',
    endorsements: ['HAZMAT', 'Tanker'],
    medicalCardExpiry: '2027-02-28',
    drugTestDue: '2026-07-28',
    availabilityNote: 'Not scheduled',
    emergencyContact: { name: 'Diane Brooks', relationship: 'Spouse', phone: '+1 (404) 555-8802' },
    documents: buildDocs(22, 'CDL-A 8629014', '2026-09-18', '2027-02-28', '2026-07-28'),
    notes: 'Drug test overdue and license expiring soon — hold from dispatch until compliance is cleared.',
    notesUpdatedBy: 'Sandra Mills',
    notesUpdatedAt: '2026-07-29',
    activity: idleActivity('drv-022')
  },
  {
    id: 'drv-023',
    name: 'Hannah Price',
    initials: 'HP',
    status: 'available',
    employmentStatus: 'unavailable',
    avatarUrl: '/images/avatars/avatar-2.webp',
    firstName: 'Hannah',
    lastName: 'Price',
    dob: '1992-06-15',
    gender: 'female',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2020-03-23',
    phone: '+1 (303) 555-7756',
    email: 'hannah.price@cargorix.com',
    address: '1144 15th St',
    city: 'Denver',
    state: 'CO',
    zip: '80211',
    homeHubId: 'wh-bronx',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'regional',
    homeTime: 'weekly',
    payType: 'hourly',
    operatingZone: 'Mountain West',
    safetyScore: 87,
    employeeId: 'EMP-1023',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-24',
    licenseNumber: 'CDL-A 8302178',
    licenseClass: 'class_a',
    licenseState: 'CO',
    licenseExpiry: '2028-03-24',
    endorsements: ['Doubles/Triples'],
    medicalCardExpiry: '2026-08-16',
    drugTestDue: '2027-04-19',
    availabilityNote: 'Off on Aug 24 – Aug 26',
    emergencyContact: { name: 'George Price', relationship: 'Parent', phone: '+1 (303) 555-1163' },
    documents: buildDocs(23, 'CDL-A 8302178', '2028-03-24', '2026-08-16', '2027-04-19'),
    activity: idleActivity('drv-023')
  },
  {
    id: 'drv-024',
    name: 'Liam Carter',
    initials: 'LC',
    status: 'available',
    employmentStatus: 'inactive',
    avatarUrl: '/images/avatars/avatar-5.webp',
    firstName: 'Liam',
    lastName: 'Carter',
    dob: '1993-01-18',
    gender: 'male',
    nationality: 'American',
    languages: ['English', 'Spanish'],
    hireDate: '2020-10-05',
    phone: '+1 (813) 555-4482',
    email: 'liam.carter@cargorix.com',
    address: '502 S Franklin St',
    city: 'Tampa',
    state: 'FL',
    zip: '33611',
    homeHubId: 'wh-newark',
    shift: 'day',
    shiftHours: '6 AM – 6 PM',
    driverType: 'local',
    homeTime: 'daily',
    payType: 'hourly',
    operatingZone: 'Gulf Coast',
    safetyScore: 84,
    employeeId: 'EMP-1024',
    weeklyOff: 'Sunday',
    nextOff: '2026-08-09',
    licenseNumber: 'CDL-A 8218605',
    licenseClass: 'class_a',
    licenseState: 'FL',
    licenseExpiry: '2027-12-09',
    endorsements: [],
    medicalCardExpiry: '2026-07-05',
    drugTestDue: '2027-05-27',
    availabilityNote: 'Not scheduled',
    emergencyContact: { name: 'Olivia Carter', relationship: 'Spouse', phone: '+1 (813) 555-9927' },
    documents: buildDocs(24, 'CDL-A 8218605', '2027-12-09', '2026-07-05', '2027-05-27'),
    activity: idleActivity('drv-024')
  },
  {
    id: 'drv-025',
    name: 'Dylan Walker',
    initials: 'DW',
    status: 'offline',
    employmentStatus: 'inactive',
    avatarUrl: '/images/avatars/avatar-7.webp',
    firstName: 'Dylan',
    lastName: 'Walker',
    dob: '1983-07-02',
    gender: 'male',
    nationality: 'American',
    languages: ['English'],
    hireDate: '2015-01-19',
    phone: '+1 (206) 555-6693',
    email: 'dylan.walker@cargorix.com',
    address: '400 Broad St',
    city: 'Seattle',
    state: 'WA',
    zip: '98115',
    homeHubId: 'wh-brooklyn',
    shift: 'night',
    shiftHours: '6 PM – 6 AM',
    driverType: 'otr',
    homeTime: 'biweekly',
    payType: 'per_mile',
    operatingZone: 'Pacific Northwest',
    safetyScore: 80,
    employeeId: 'EMP-1025',
    weeklyOff: 'Friday',
    nextOff: '2026-08-08',
    licenseNumber: 'CDL-A 8091447',
    licenseClass: 'class_a',
    licenseState: 'WA',
    licenseExpiry: '2026-07-15',
    endorsements: ['HAZMAT'],
    medicalCardExpiry: '2027-03-08',
    drugTestDue: '2026-11-20',
    availabilityNote: 'On extended leave',
    emergencyContact: { name: 'Megan Walker', relationship: 'Sibling', phone: '+1 (206) 555-2218' },
    documents: buildDocs(25, 'CDL-A 8091447', '2026-07-15', '2027-03-08', '2026-11-20'),
    notes: 'On extended leave of absence. License lapsed — must renew and re-certify before reactivation.',
    notesUpdatedBy: 'Denise Faulkner',
    notesUpdatedAt: '2026-07-20',
    activity: idleActivity('drv-025')
  }
]

const TYPE_LABEL: Record<Vehicle['type'], string> = {
  truck: 'Truck (Container)',
  van: 'Cargo Van',
  reefer: 'Reefer',
  motorcycle: 'Motorcycle'
}

const vehicleByDriverId = new Map<string, Vehicle>()

for (const vehicle of vehiclesDb) {
  if (vehicle.assignedDriverId && !vehicleByDriverId.has(vehicle.assignedDriverId)) {
    vehicleByDriverId.set(vehicle.assignedDriverId, vehicle)
  }
}

const toAssignedVehicle = (vehicle: Vehicle): DriverAssignedVehicle => ({
  vehicleId: vehicle.id,
  vehicleNo: vehicle.registrationNo ?? vehicle.id,
  make: vehicle.make ?? '—',
  model: vehicle.model ?? '—',
  typeLabel: TYPE_LABEL[vehicle.type],
  year: vehicle.year ?? 2024,
  capacityLabel: `${vehicle.capacityTons} Ton`,
  registrationDate: `${vehicle.year ?? 2024}-03-10`
})

const decorate = (driver: Driver): Driver => {
  const vehicle = vehicleByDriverId.get(driver.id)

  if (!vehicle) return { ...driver, assignedVehicle: undefined, currentAssignment: undefined }

  const assignment = vehicle.currentAssignment
  const origin = assignment?.origin ?? 'Newark Hub'
  const destination = assignment?.destination ?? vehicle.nextStopLabel ?? 'Newark Hub'

  return {
    ...driver,
    assignedVehicle: toAssignedVehicle(vehicle),
    currentAssignment: assignment && {
      routeId: assignment.routeId,
      routeName: assignment.routeName,
      shipmentId: assignment.shipmentName,
      cargo: `${vehicle.stopsTotal} stops · ${vehicle.currentLoadKg?.toLocaleString() ?? 0} kg`,
      origin,
      destination,
      nextStop: assignment.nextStop,
      nextStopDistance: vehicle.distanceRemainingKm ? `${vehicle.distanceRemainingKm} km away` : undefined,
      etaLabel: assignment.etaLabel
    },
    tripHistory: driver.tripHistory && buildTrips(driver.id, origin, destination, 42, '1h 25m', 77800)
  }
}

export const db: Driver[] = authored.map(decorate)
